### ISSUE TITLE
web3 send tx always time out

### ISSUE THREAD

**Issue by mtyou** [Fantom-foundation/go-opera#103]
from 30 hour ago,when we use web3  send the tx, the only response is timeout, but use metamask is ok,i dont konw why,many people have the same question,we talk in the discord  developers-chat, but no one support to this delay。i think there is some problem in Fantom NET,please check it ,and reply us in the discord  developers-chat,thank you!

by the way ,there is somebody Spamming Fantom network,you can see this address https://ftmscan.com/address/0x3a3871182c1e38f30870e2bf4711b519c590fe49, receive little ftm everytime,only two day, it have produce 578900 transactions , maybe it cast the delay.

**Comment by uprendis** [comment]
Hello @mtyou,
Good day to you!

You would have to increase gas price of your transactions to compete with the spamming transactions. Still, if your transactions has large gas limit, it might take a while for it to get originated when none of validators has enough of spare `gas power` for origination

**Comment by mtyou** [comment]
thank you,with your help ,it has work well 。
