### ISSUE TITLE
Running archive node with --syncmode full --gcmode archive throws error 'flag provided but not defined: -syncmode'

### ISSUE THREAD

**Issue by gebrits** [Fantom-foundation/go-opera#153]
**Describe the bug**
Trying to run Go-opera as full archive node. Assuming this is similar to starting a regular Geth (ethereum) archive node, which seems to be right judging from available commandline-options, I should run go-opera with (among other things) `--syncmode full --gcmode archive`

Doing this however throws immediately with error: `flag provided but not defined: -syncmode`

**To Reproduce**
Run: `/root/go-opera/build/opera --syncmode full --gcmode archive --nousb`

**Expected behavior**
Go-opera should run in full archive node

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 
 - Go Opera: 1.0.1-rc.1

**Comment by uprendis** [comment]
Hello @gebrits,
Good day to you!

**Comment by gebrits** [comment]
Ah, I saw that link of importing history, but didn't understand where it would fit in. Now it does awesome. 

To verify: I'm already quite a long way in syncing. Can the history be loaded at any time? Or do I have to first load the history and start syncing afterwards?

**Comment by uprendis** [comment]
You can import the history at any time
