### ISSUE TITLE
Docker image fails to build

### ISSUE THREAD

**Issue by Valatka** [Fantom-foundation/go-opera#154]
Then building the docker image from the docker directory, the image fails to build on step 6:
``RUN go mod download`` 
Error:
```go: github.com/dvyukov/go-fuzz@v0.0.0-20201127111758-49e582c6c23d (replaced by github.com/guzenok/go-fuzz@v0.0.0-20210103140116-f9104dfb626f): version "v0.0.0-20210103140116-f9104dfb626f" invalid: unknown revision f9104dfb626f```

**Comment by rus-alex** [comment]
Hello @Valatka ,
Good day to you!
It seems to work for us. Could you please collect and give additional logs for us to figure out?
Run the `make opera-image` on https://github.com/Fantom-foundation/go-opera/tree/debug/issue154 branch, please.

**Comment by Valatka** [comment]
Okay, so the issue was that I was building the docker image manually and not using the config provided in the Makefile.
