### ISSUE TITLE
Missing parent trace

### ISSUE THREAD

**Issue by ninjascant** [Fantom-foundation/go-opera#160]
**Describe the bug**
There are transactions in which traces are not consecutive, i.e. some of the traces don't have a parent trace

**To Reproduce**
Example of such of tx: `0xc2e019c1ea85b92ef0a34b1f1b16d6eced3046846eb5bce1b5fb1bf0ef62968a`

Below is a script that extract trace addresses for traces from this tx:

```
import requests

res = requests.post(
    'https://rpcapi-tracing.fantom.network/',
    json={
        'jsonrpc': '2.0',
        'method': 'trace_transaction',
        'params': ['0xc2e019c1ea85b92ef0a34b1f1b16d6eced3046846eb5bce1b5fb1bf0ef62968a'],
        'id': 1
    }
).json()['result']

trace_addresses = [trace['traceAddress'] for trace in res]

for address in trace_addresses:
    print(address)
```

The output of a script is the following:
```
[]
[0]
[1]
[2]
[3]
[4]
[4, 0]
[4, 1]
[4, 1, 0]
[4, 1, 1]
[4, 1, 2]
[4, 1, 3]
[4, 1, 3, 0]
[4, 1, 3, 1]
[4, 1, 3, 2]
[4, 1, 4]
[4, 1, 5]
[4, 1, 5, 0]
[4, 1, 5, 1]
[4, 1, 5, 2]
[4, 1, 6]
[4, 2]
[4, 3]
[5, 3]
```

**Expected behavior**
The trace with `traceAddress` [5, 3] should have trace address `[5]` or there should be traces with trace addresses `[5]`, [5, 0]`, `[5,1]`, `[5,2]`

**Comment by quan8** [comment]
@ninjascant Is it still the case?
