### ISSUE TITLE
newPendingTransactions subscription receiving already validated transactions

### ISSUE THREAD

**Issue by redline-finance** [Fantom-foundation/go-opera#168]
**Describe the bug**
The newPendingSubscriptions filter/subscription should emit tx hashes that are still to be validated, but instead, it emits transactions that are already validated and have a block number assignated.

**To Reproduce**
Subscribe to `newPendingTransactions` and check received tx hashes.

It looks like the code emitting the txhashes is in the EndBlock function, where transactions have already been executed and so on

**Comment by uprendis** [comment]
Hello @redline-finance,
Good day to you!
You're right, thank you for pointing it out!
If you don't mind running experimental code, please try this branch: https://github.com/uprendis/go-opera/tree/feature/fix-pendings-txs-subscription

**Comment by redline-finance** [comment]
That seems to work great in our tests.

Thanks!
