### ISSUE TITLE
Is there any way to speed up the synchronization? I've been syncing for a month and I haven't caught up with the node

### ISSUE THREAD

**Issue by jakyalan** [Fantom-foundation/go-opera#170]

**Comment by soltrac** [comment]
You can sync up nowadays with a NVME in 1 week more or less. You need a more capable hardware

**Comment by jakyalan** [comment]
> You can sync up nowadays with a NVME in 1 week more or less. You need a more capable hardware

What hardware is recommended? I now have a 16-core 32GB 4T SSD

**Comment by Snake4life** [comment]
> You can sync up nowadays with a NVME in 1 week more or less. You need a more capable hardware

whats the current size?

**Comment by jakyalan** [comment]
> > You can sync up nowadays with a NVME in 1 week more or less. You need a more capable hardware
> 
> whats the current size?

I am now synchronized to 943G
> ftm.syncing
{
  currentBlock: 17374829,
  currentBlockHash: "0x00008f4d0000045eb6985ac9d7210a18c4f0c93fa92935b2e9c2aaedcb17ab14",
  currentBlockTime: "0x16a69643a1527b3f",
  currentEpoch: "0x8f4d",
  highestBlock: 17851171,
  highestEpoch: "0x97fb",
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 0
}

**Comment by carrie143** [comment]
Did you solve？I have the same question

**Comment by quan8** [comment]
Please contact our support on Discord or TG.
