### ISSUE TITLE
This repo has no "About"

### ISSUE THREAD

**Issue by tredondo** [Fantom-foundation/go-opera#180]
"No description, website, or topics provided." at https://github.com/Fantom-foundation/go-opera

**Comment by quan8** [comment]
Hi @tredondo , you may see the project's REAME file and wiki pages.

**Comment by tredondo** [comment]
Thanks, the point was to make the repo look professional and searchable from GitHub. Thanks for doing that!

These two repos could also benefit from a website and description, respectively:
https://github.com/Fantom-foundation/tokensale
https://github.com/Fantom-foundation/bnbridge.exchange
