### ISSUE TITLE
getPastLogs returns validated logs when "pending" is provided

### ISSUE THREAD

**Issue by d-rek** [Fantom-foundation/go-opera#185]
Good day! I noticed the following during testing with a remote node.

**Problem**
When using getPastLogs (https://web3js.readthedocs.io/en/v1.5.2/web3-eth.html?highlight=logs#getpastlogs) and providing `pending` to both `fromBlock` and `toBlock`, the RPC node returns validated transaction logs instead of pending logs.

**Reproduction steps**
Although pending logs are requested, the following request returns logs from validated transactions:

`curl https://rpc.ftm.tools -X POST --data '{"method":"eth_getLogs","params":[{"fromBlock": "pending", "toBlock": "pending"}],"id":1,"jsonrpc":"2.0"}'`

**Comment by uprendis** [comment]
Hello @d-rek,
Good day to you!

**Comment by d-rek** [comment]
Hey @uprendis, that makes sense. Thank you for the clarification!
