### ISSUE TITLE
Quick/fast sync

### ISSUE THREAD

**Issue by ceds** [Fantom-foundation/go-opera#191]
Is there any way to do a quick/fast sync similar to "fast sync" with GETH?  I don't see anything in the command line help.  My "normal" sync created a full node which is not what I'm looking for.

**Comment by uprendis** [comment]
Hello @ceds,
Good day to you!
We may introduce the auxiliary consensus mechanism called LLR and snapsync support in the next major release

**Comment by ceds** [comment]
That's very good news.  Thank you for letting me know
