### ISSUE TITLE
Low speed download snapshot

### ISSUE THREAD

**Issue by Timofeyeff** [Fantom-foundation/go-opera#193]
Hi all! I want to dowloaded snapshot from https://download.fantom.network/opera_pruned_19nov21.tgz, but download speed only 50 kb/s, and ETA is 40 days. Were i may download snapshot with normal speed.
Regards, Maksim

**Comment by millerjohnp** [comment]
I'm also experiencing this issue. Is there another place to download the snapshot? Or is it possible to speed up the download?

**Comment by quan8** [comment]
@Timofeyeff @millerjohnp 
You may try:
https://download.fantom.network/opera_pruned_14dec21.tgz
or
https://snapshot.fantom.network/opera_pruned_14dec21.tgz

For further support, please contact our support team. Thanks.
