### ISSUE TITLE
trace_transaction for txs creating contracts via proxy shows the implementation as the context/creator

### ISSUE THREAD

**Issue by Enigmatic331** [Fantom-foundation/go-opera#196]
With a tx where a proxy delegateCalls to a factory contract which creates a child contract, on FTM's trace_transaction the creator is the implementation contract, instead of the proxy contract itself.

This conceptually differs vs OE's trace_transaction (and Geth trace) where the trace result points back to the proxy contract as the originating context, hence the proxy contract being the creator of the child contract.

E.g. the below two txs:

https://kovan.etherscan.io/vmtrace?txhash=0xc4aa87dfabd34ef4a0ef677b7c3e272b5b67bc4d7e6d97c76d0d7c225f9a08ea&type=parity#raw

https://ftmscan.com/vmtrace?txhash=0xf0fe376bf2bc801d5d7c571f823e0b3681f201ae5f4dbc22d24667d72a6d5eb8&type=parity#raw

More specifically - Note the "from" and "to":
![image](https://user-images.githubusercontent.com/28551011/146424168-56a64dc4-319e-4bc0-8590-14b54b89b1a9.png)

Since delegateCall refers to the proxy contract as the context, should the proxy contract not be the contract creator?

Much thanks. :pray:

**Comment by HonzaDajc** [comment]
I understand your point, but there is no detailed specification for the OE's trace module. Our implementation is more transparent as you can see true contract creator in the trace. So in case the implementation will change in time, you'll be still able to see the original creator easily in the trace.
