### ISSUE TITLE
[Feature request] Add binaries

### ISSUE THREAD

**Issue by mikhail-khalizev** [Fantom-foundation/go-opera#203]
Please add compiled binaries of the program for Linux and Windows in releases.

**Comment by mikhail-khalizev** [comment]
For example, as it made in [bsc](https://github.com/binance-chain/bsc/releases):

![image](https://user-images.githubusercontent.com/18654696/146805170-d502bad0-9c3d-4fc5-a72d-d8f134ca0120.png)

**Comment by quan8** [comment]
Hi @mikhail-khalizev , Thanks for the suggestion. It's best to compile the code to your current environment.

If you're interested in running a node, please check:
https://github.com/Fantom-foundation/go-opera/wiki/Running-a-Fantom-node
