### ISSUE TITLE
Datadir snapshot / backup and state flush

### ISSUE THREAD

**Issue by gab-nando** [Fantom-foundation/go-opera#209]
I'm trying to backup the datadir of a read-only node and I run into issues with data consistency:
```
Fatal: Failed to make engine: failed to open existing databases: dirty state: genesis: 0016C495DD4EEDF6A9,
gossip: DE0016C495E2BCC3CF4A16C495E2E9B1D823
```

My understanding is that this can happen if the backup of the underlying storage takes place during a state flush. Is it correct?

Is it there a way to take a consistent backup of the datadir? Would it be possible to expose an /admin/state/flush endpoint to be able to (externally) trigger the flush prior to the backup?

**Comment by uprendis** [comment]
Hello @gab-nando,
Good day to you!
Yeah, your understanding is correct. Currently the only safe way to backup the datadir is to stop the node, make the backup, start the node again

**Comment by vlads123** [comment]
Hello

Is there a plan to "fix" this, just to be able to backup nodes on the fly (without stopping it) ????

This is very important for node operators, cos stopping node == downtime, which is not desirable.

**Comment by kajeagentspi** [comment]
@vlads123 I don't think there is any way to do a backup while the node is running. AFAIK even geth doesn't have this feature.

**Comment by vlads123** [comment]
@kajeagentspi FYI
I can say for sure that at least the following go-ethereum based chains Heco, BSC, Ethereum can be backued up with disk snapshot on the fly
openethereum supports it as well 

And the feature looks pretty basic for such kind of software - at least from operations point of view

**Comment by uprendis** [comment]
We can add this feature on the level of KV dabases. Yet, such on-the-fly backup will take much more time than a simple file system backup
It's not very simple to do on-the-fly in the realm of a file system because we currently have a DB layout where we accumulate changes in memory, and then flush them "atomically" to disk. If you take a backup which corresponds to a middle of such a flush- then you get the error above
