### ISSUE TITLE
trace_transaction reverting on subtrace even when the subtrace successfully created a contract

### ISSUE THREAD

**Issue by Enigmatic331** [Fantom-foundation/go-opera#218]
**Describe the bug**
And I'm back! 😁 (sorry)

In summary: When we run trace_transaction on a specific tx (https://ftmscan.com/tx/0x9d8c6117d0671041df7d76ea44dfe406dc1455e8d204fc2bee82908d6955a58b), subtraces creating contracts show up as "reverted", however contracts were indeed created and can be confirmed with the presence of on-chain bytecode.

Trace from FTMscan: https://ftmscan.com/vmtrace?txhash=0x9d8c6117d0671041df7d76ea44dfe406dc1455e8d204fc2bee82908d6955a58b&type=parity#raw

The subtrace in question being the two "create" subtraces, at index [3, 6, 9] and [3, 7]:

![image](https://user-images.githubusercontent.com/28551011/150487781-5df8e1e4-9dd4-4956-87e8-f16b4bed61ce.png)

![image](https://user-images.githubusercontent.com/28551011/150487826-a976b4f1-86f5-4d4e-8ac6-8c96879d982a.png)

These two traces create contracts on both https://ftmscan.com/address/0xcbba8c0645ffb8aa6ec868f6f5858f2b0eae34da and https://ftmscan.com/address/0x18f1de40c5056ffe75df809f1f9441f539376e1b (can be confirmed with eth_getCode), which unfortunately wouldn't show up as contracts on FTMscan as the revert means the result.address attribute wouldn't be available for consumption.

Both contracts having on-chain bytecode:
![image](https://user-images.githubusercontent.com/28551011/150488559-d13454cc-31d7-4c4c-83fb-aae478952a86.png)

OTOH, this seems to be traced correctly on Tenderly: https://dashboard.tenderly.co/tx/fantom/0x9d8c6117d0671041df7d76ea44dfe406dc1455e8d204fc2bee82908d6955a58b

Feel free to let me know if there might be any additional information required, much thanks!

**Comment by HonzaDajc** [comment]
Hi @Enigmatic331, thanks for your feedback. You are right and there was a problem with hadnling try/catch of the reverting inner call. We did a fix, but it will take some time to get it on the servers with new version.

**Comment by Enigmatic331** [comment]
Thanks so much @HonzaDajc ! Feel free to ping us once there's a release, and we can update our nodes (+ reindex the affected areas) for FTMscan as well.

**Comment by HonzaDajc** [comment]
Fix is now present in release/txtracing/1.0.2-rc.7 so if you update your nodes with this updated version, then revert should work as expected.

**Comment by quan8** [comment]
@Enigmatic331  pushed a new branch release/txtracing/1.0.2-rc.8.

**Comment by Enigmatic331** [comment]
Hmm we have pushed 1.0.2-rc.8 to our servers and had a test, seems like the same issue is still persisting (tested using txhash 0x9d8c6117d0671041df7d76ea44dfe406dc1455e8d204fc2bee82908d6955a58b).

[tracedump_20220208.txt](https://github.com/Fantom-foundation/go-opera/files/8020723/tracedump_20220208.txt)

Any chance the tracing node hosted by Fantom is updated already? (https://rpcapi-tracing.fantom.network/)

**Comment by HonzaDajc** [comment]
@Enigmatic331 As I can see, you have tested it on a 21 days old transaction. You will see it working on transactions which are created after the fix was applied to the node. For the transactions before fix was applied, node needs full sync from the start, because traces are created and stored as the transaction is processed by the node for the first time. 
Nodes at tracing api endpoint were not yet patched with this as we are waiting for another things to be done and then we will do the full resync.

**Comment by SayWhatDev** [comment]
Hey @HonzaDajc , I was wondering is there an ETA on when the patch will be applied and the full resync? Just as information we are using the following rpc endpoint for the deployment: https://rpc.ftm.tools.

**Comment by jsvisa** [comment]
same issue with this tx: https://ftmscan.com/tx/0xa5305194db03720d6d79204e097daeaa7a00a0297280401abcb6a7c5e56045c8 

```
fantom: fantom-1.0.2
```

**Comment by jsvisa** [comment]
@HonzaDajc IMHO, the traces were not stored within the transaction, it was replayed when `trace_transaction` is invoked.

And I'm running [txtracing-1.1.0-rc.3](https://github.com/Fantom-foundation/go-opera/tree/release/txtracing/1.1.0-rc.3), and this tx(within a 1day)  https://ftmscan.com/tx/0xcdf45a17bae5d1b8ca9bcfb0160c54f4fe043b5a3d79dd9f165e596075dfc103 also have this issue.

> @Enigmatic331 As I can see, you have tested it on a 21 days old transaction. You will see it working on transactions which are created after the fix was applied to the node. For the transactions before fix was applied, node needs full sync from the start, because traces are created and stored as the transaction is processed by the node for the first time. Nodes at tracing api endpoint were not yet patched with this as we are waiting for another things to be done and then we will do the full resync.

**Comment by HonzaDajc** [comment]
Hi @jsvisa , 

> @HonzaDajc IMHO, the traces were not stored within the transaction, it was replayed when `trace_transaction` is invoked.
> 
> And I'm running [txtracing-1.1.0-rc.3](https://github.com/Fantom-foundation/go-opera/tree/release/txtracing/1.1.0-rc.3), and this tx(within a 1day) https://ftmscan.com/tx/0xcdf45a17bae5d1b8ca9bcfb0160c54f4fe043b5a3d79dd9f165e596075dfc103 also have this issue.
> 

This transaction is failing because of "out of gas" so it is different from the case in this thread. So please if you think, that it is wrong, create new issue for this. But I think, that this behavior is correct in this case. If I compare it with another tracer, then it is also saying, that whole tx failed.
