### ISSUE TITLE
Transaction sorting rules？ 

### ISSUE THREAD

**Issue by qinxg** [Fantom-foundation/go-opera#226]
I found that the transactions were not sorted according to gas price
What are the rules?

https://ftmscan.com/txs?block=29162307

**Comment by uprendis** [comment]
Transactions in events are sorted by gas price by each individual validators. Events emitted by validators are merged into a block by the consensus algorithm, which sorts them rather chronologically (as much as their causality may be derived from the DAG)

**Comment by qinxg** [comment]
> Transactions in events are sorted by gas price by each individual validators. Events emitted by validators are merged into a block by the consensus algorithm, which sorts them rather chronologically (as much as their causality may be derived from the DAG)

------------------------
I want to learn the relevant code. Which part is it implemented in?
