### ISSUE TITLE
historical data AND  opera snapshot prune-state

### ISSUE THREAD

**Issue by masayil** [Fantom-foundation/go-opera#228]
Can I get the historical data after I run the command `opera snapshot prune-state` ?

**Comment by uprendis** [comment]
Hello @masayil,
Good day to you!
In a case you mean accessing contract data (or balances/nonces data) from past blocks, then no. If you pruned at block B, then you won't be able to access this data for blocks < B, only for blocks >= B

**Comment by uprendis** [comment]
You will still be able to access blocks, receipts and search logs

**Comment by masayil** [comment]
thx
