### ISSUE TITLE
tesetnet fail to sync

### ISSUE THREAD

**Issue by masayil** [Fantom-foundation/go-opera#251]
time: 17:00  2022/2/11 UTC+8
![image](https://user-images.githubusercontent.com/65291464/153569155-fb5c4b8d-e796-42d8-92f1-903b8450503d.png)

1)I delete the old datadir .
2) restart node
`/root/svc/opera --genesis /root/svc/testnet.g --nousb --http --http.addr '0.0.0.0' --http.port 8545 --http.corsdomain "*" --http.vhosts "*" --ws --ws.addr '0.0.0.0' --ws.port 8546  --ws.origins '0.0.0.0' --graphql --graphql.corsdomain '*' --graphql.vhosts '*' --datadir "/root/svc/node" --bootnodes "enode://2672dd6d009dc090b24b4a8c5c51466d2194c554d4213ae873d5cb8ed14f2bedf940200559e31756855d52462963328c2dde9ffcba23961a26ec7d63cc687e43@163.172.144.218:54722,enode://7c6beb930aa9e2e5081db2913095a00303d8db1a7691ad2d8156e62e47390d8d703b939ca0eb3b80becc9315c7dcaccffb7a7b3cb61b2543bbe0613bcfe637e1@151.106.62.7:59608" --http.api "net,eth,web3" --ws.api "net,eth,web3" --syncmode full`
3) import evm history

But I cannot find peer now.

**Comment by uprendis** [comment]
Hello @masayil,
Good day to you!
That's a result of London upgrade activation on public testnet. You have to upgrade to `release/1.1.0-rc.3`, which is a latest pre-release version for testnet. Since you missed the upgrade, you have to also resync

**Comment by uprendis** [comment]
=> But I cannot find peer now
Please wait a bit longer. It takes longer to find first peers in public testnet than in mainnet

**Comment by masayil** [comment]
> => But I cannot find peer now Please wait a bit longer. It takes longer to find first peers in public testnet than in mainnet

I have been running opera for 13 hours. Is it normal?
![image](https://user-images.githubusercontent.com/65291464/153692297-8c9d3236-4081-461e-bc36-057dc0be6654.png)
