### ISSUE TITLE
Can't call debug_traceTransaction

### ISSUE THREAD

**Issue by wzglgo** [Fantom-foundation/go-opera#255]
brach is remotes/origin/release/txtracing/1.1.0-rc.3
start.sh add "--tracenode" afer "--tracing"
start is successful but when i call debug_traceTransaction 
return
`{
    "jsonrpc": "2.0",
    "id": 2,
    "error": {
        "code": -32601,
        "message": "the method debug_traceTransaction does not exist/is not available"
    }
}`
thx

**Comment by quan8** [comment]
Hi @wzglgo , are you running it on the testnet?

**Comment by wzglgo** [comment]
> Hi @wzglgo , are you running it on the testnet?

i'm running demo/start.sh
it's looks like fakenet

**Comment by cyberbono3** [comment]
When I  run `./demo/start.sh --tracing --tracenode` in mentioned branch,  it outputs                                                      `./start.sh: line 28: syntax error near unexpected token >`.                                                                                                                 It looks like one `>` is redundant [here](https://github.com/Fantom-foundation/go-opera/blob/release/txtracing/1.0.1-rc.3/demo/start.sh#L29) and should be removed.

**Comment by cyberbono3** [comment]
@wzglgo Can you share the full command for calling `debug_traceTransaction`, please?

**Comment by wzglgo** [comment]
About syntax error in start.sh,like you said  one > should be removed.
<img width="774" alt="image" src="https://user-images.githubusercontent.com/95947852/155641003-8f9972ed-a23b-4fed-8cf1-04a352ef320b.png">
I'm sure the debug api is opened @cyberbono3

**Comment by mojitoce** [comment]
I also have this problem when running the node with --tracing and --tracenode flags. Is there anything else I have to enable?

**Comment by cyberbono3** [comment]
@wzglgo The problem might be in your empty `params`. Please see this [post](https://ethereum.stackexchange.com/questions/9434/calling-debug-tracetransaction-from-web3-api) for more information.

**Comment by wzglgo** [comment]
> @wzglgo问题可能出在您的 empty`params`中。请参阅这篇[文章](https://ethereum.stackexchange.com/questions/9434/calling-debug-tracetransaction-from-web3-api)了解更多信息。

Run in console
<img width="547" alt="image" src="https://user-images.githubusercontent.com/95947852/156119335-f90c7600-d7aa-485d-a53a-161c1622c5d0.png">

**Comment by quan8** [comment]
Hi @wzglgo , it will be added in future releases.

**Comment by hkalina** [comment]
Hi @wzglgo, you need to use `release/txtracing/1.1.0-rc.4` - the rc.3 did not provide the debug_trace api yet.
Params `--tracing` and `--tracenode` are NOT needed for debug_trace commands, they are relevant for the tracing api only.

**Comment by quan8** [comment]
Hi @wzglgo  does it work now? can we close this issue?
