### ISSUE TITLE
Gas free network

### ISSUE THREAD

**Issue by arguiot** [Fantom-foundation/go-opera#257]
**Is your feature request related to a problem? Please describe.**
Using Opera as a playground (private net) for developing dApps without having to mint FTM would be awesome.

**Describe the solution you'd like**
Make it possible to run a fakenet/private network that doesn't require gas to work.

**Describe alternatives you've considered**
Either make it a flag in the configuration or in the command line.

**Comment by quan8** [comment]
Hi @arguiot , you may run a fakenet.
