### ISSUE TITLE
Looking for peers at testnet

### ISSUE THREAD

**Issue by julia-light** [Fantom-foundation/go-opera#260]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/54106236/156909001-8b83c993-4acb-4631-ac22-d050e5cb98ae.png">

When deploying testnet node, the node has been stuck in the step of `looking for peers`

```
[root@fantom-testnet-01 ~]# curl 127.0.0.1:8545 -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":0}'
{"jsonrpc":"2.0","id":0,"result":"0x7505e"}
```

**Comment by uprendis** [comment]
Please try again, it looks there was a shortage of nodes which advertise their IP in discovery
