### ISSUE TITLE
Genesis creation of fakenet in opera

### ISSUE THREAD

**Issue by Neoblock8** [Fantom-foundation/go-opera#261]
Hi,
 How to create genesis file and set premine for fakenet in opera?
 In below link, they provide 'lachesis' as localnet
  https://docs.fantom.foundation/tutorials/create-a-local-test-network

**Comment by uprendis** [comment]
Currently it's not possible with the default tools unfortunately. Soon we'll release a reworked genesis file format. After that, setting up a new genesis file should become easier
