### ISSUE TITLE
Calibrate logging verbosity levels to match "Basic RPC" use case

### ISSUE THREAD

**Issue by 0xidm** [Fantom-foundation/go-opera#269]
**Is your feature request related to a problem? Please describe.**

The sensitivity of the logging verbosity should be re-calibrated for common use cases.  In `v1.0.2-rc.5` the logs become flooded with new event messages, which are not helpful for running a basic rpc.

Logging verbosity is controlled with the `--verbosity` flag.  When verbosity is 1, only errors are shown.  The default verbosity is 3, which refers to informational messages.  Values above 3 are used for debugging, with verbosity=5 referring to the greatest logging detail that could be requested.

The problem with the default verbosity of 3 is that it is much too verbose.  In particular, each `event` message is logged with the "info" level - so it is included with verbosity=3.  `New Event` messages should probably be moved to a higher log level (e.g. 4 or 5) because these messages are extremely common and flood the logs with hundreds of entries per minute; potentially gigabytes of logs per day.

Meanwhile, setting verbosity=2 (i.e. warnings) results in absolutely no messages being logged.  From the logs, it is not even possible to tell that the daemon has started when the verbosity is less than 3.

**Describe the solution you'd like**

- re-classify "new event" log messages as debug messages (verbosity=5), not info (verbosity=3)

**Describe alternatives you've considered**

- consider setting verbosity=2 by default and ensuring that this log level produces some diagnostic feedback.  I don't personally like this alternative.

**Additional context**

Currently using opera v1.0.2-rc.5.  I am trying to run a local RPC, not a validator.  I expected the output to be similar to that of go-ethereum, which produces a few log entries per minute.  In particular, I expected to see notices about new blocks in the logs.

Without better control of logging verbosity, it is pretty hard to do basic administration with the opera client.  The new event messages flood the logs with messages I would like to be able to filter out.

**Comment by quan8** [comment]
@0xidm Please use 1.0.2-rc.7. Btw, we're about to upgrade to 1.1.0.
