### ISSUE TITLE
add back the argument --snapshot=false

### ISSUE THREAD

**Issue by jsvisa** [Fantom-foundation/go-opera#274]
**Is your feature request related to a problem? Please describe.**

snapshot sync for archive node is slowly, Too much time was spent generating the State Snapshot process

```
INFO [03-18|13:08:05.532] Generating state snapshot                root=5377b3..10c45c at=7823d7..d5b4bf accounts=992,673 slots=71,257,066 storage=4.97GiB    elapsed=9h55m44.756s eta=15h47m17.75s
```
Should we add back the `--snapshot=false` arg?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by uprendis** [comment]
Hello @jsvisa,
Good day to you!
Unfortunately snapshot is needed for snapsync. Due to that, we erased the option

**Comment by jsvisa** [comment]
@uprendis thanks for your quick replay, but I'm running the trace node in full-sync, not snap-sync, so I don't think snapshots are needed in this case. Also in Geth this argument is keeped.
