### ISSUE TITLE
[project structe] why filter and gasprice package is under gossip dir?

### ISSUE THREAD

**Issue by huahuayu** [Fantom-foundation/go-opera#276]
Hi, I am studying fantom code, I am a little confused, why `filter` and `gasprice` package is under `gossip` dir, as per my understanding gossip is a p2p protocol, noting to do with high-level terms like `filter` and `gasprice`

![image](https://user-images.githubusercontent.com/1725060/159128559-21ab97c6-79bc-48a0-bd4a-8fa6fd02c5ee.png)

**Comment by uprendis** [comment]
Hello @huahuayu,
Good day to you!
I agree that `gossip` a misnamed module

**Comment by Administratordes** [comment]
Kindly open this live chat to talk to the customer service directly on your issue  https://direct.lc.chat/14065185/
