### ISSUE TITLE
where is the block fetcher 

### ISSUE THREAD

**Issue by huahuayu** [Fantom-foundation/go-opera#277]
Hi, I am studying go-opera code, I can see there is txFetcher but there is no block fetcher as ethereum dose, so where is the block receive logic.

And in `go-opera/gossip/handler.go` https://github.com/Fantom-foundation/go-opera/blob/10ca669279e26d21133c1d95db26ea41a6479360/gossip/handler.go#L651 it has`EvmTxsMsg` but don't have a `blockMsg` dealing logic.

I try to look into the lachesis-base logic but don't understand it yet.

**Comment by uprendis** [comment]
Hello @huahuayu,
Good day to you!
Block isn't an actual consensus message in Lachesis consensus, it's only an abstraction defined as a batch of finalized events. Events are consensus messages

**Comment by huahuayu** [comment]
Thanks for the reply, kind of get the concept, but can you please specify the code line reference here, where is the logic the peer received the batch of finalized events in the first place.

**Comment by huahuayu** [comment]
Thanks @uprendis , you wrote a great document, I will check the code in detail later

**Comment by Administratordes** [comment]
Kindly open this live chat to talk to the customer service directly on your issue  https://direct.lc.chat/14065185/
