### ISSUE TITLE
Signed transaction queued forever

### ISSUE THREAD

**Issue by dsbrgg** [Fantom-foundation/go-opera#279]
**Describe the bug**I
I've been testing transactions with a fantom node on localnet. So far, transactions seems to be working as expected but I've realised that funds are not moving and upon inspecting `txpool.contents` I see all my transactions being queued and never leaving that state.

- go-opera 1.0.5-rc5

**To Reproduce**
1. Start 2 nodes
2. Move funds from validator to a newly created account that was added with `personal.importRawKey`
3. Make a signed transaction (I'm using `ethersproject` library to do that programatically) to another random address.
4. `txpool.status` or `txpool.contents` and `ftm.getTransaction` will show that the transaction will stay in queue forever even though new events and blocks are being generated.

**Expected behavior**
Signed transactions are instantly or almost instantly confirmed.

**Screenshots**
![Screenshot 2022-03-25 at 21 39 36](https://user-images.githubusercontent.com/25888358/160207931-ac7334e8-c036-4348-838c-cec0ceb31a50.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6.4

**Comment by quan8** [comment]
Hi @dsbrgg , Please check the gasPrice specified in your txn. Txns with high gas price have more priority.

You may check the current gas prices at:
https://api.ftmscan.com/api?module=gastracker&action=gasoracle&apikey=YourApiKeyToken
Please adjust the txn's gasPrice accordingly before you send to the network (or to send to MM for approval).

**Comment by dsbrgg** [comment]
Hello @quan8 like I mentioned, the transaction is being made on **localnet** and I'm always getting gasPrice/gasLimit based on the EVM RPC API, which both always return the same value:

```
gas: "0x5208",
gasPrice: "0x3b9aed28",
```

Also I've noticed that this happened basically with signed transactions but regular transactions seems to work.

**Comment by dsbrgg** [comment]
Hello @quan8!
Just wanted to point out that it was an issue from my side, using a nonce that was way too big instead of verifying the transaction count from the chain. I'll be closing the issue.

Thanks!
