### ISSUE TITLE
About 1.1.0-rc.4 release

### ISSUE THREAD

**Issue by kaber2** [Fantom-foundation/go-opera#280]
Hello,

I'm wondering about the 1.1.0-rc.4 release. The previous ones explicitly stated that they're only intended for testnet. How about this one? Is it safe/intended to run on mainnet?

Thanks!

**Comment by quan8** [comment]
Hi @kaber2 , yes, you can use it for both mainnet and testnet nodes.

**Comment by patllc** [comment]
I encountered "Snapshot extension registration failed" when using snap mode in mainnet.
May I advise how to fix it?

**Comment by mtyou** [comment]
> I encountered "Snapshot extension registration failed" when using snap mode in mainnet. May I advise how to fix it?

i have the same problem @quan8

**Comment by uprendis** [comment]
Hello All,
Good day to you!
In a case you were using `--syncmode snap` argument, then please note this mode won't be fully supported until LLR activation on mainnet
This error is not critical and signals that another peer doesn't behave accordingly. We'll change it to warning message in a future version

**Comment by Administratordes** [comment]
Kindly open this live chat to talk to the customer service directly on your issue  https://direct.lc.chat/14065185/

**Comment by quan8** [comment]
To use snapsync, please check use release/1.1.1-rc.1.
More info can be found in this page: https://docs.fantom.foundation/node/intro-to-snapsync
