### ISSUE TITLE
Question: Excessive "useless peers" in opera devp2p sub-protocol

### ISSUE THREAD

**Issue by JVillella** [Fantom-foundation/go-opera#282]
I've been monitoring devp2p traffic on Fantom and noticed that many peers my node is connecting to close their connection with the "useless peer" reason. What's particularly strange is that they send tx/txHashes to us for a few seconds and then claim my peer is useless.

Any ideas why this is happening? I looked at all places this `p2p.DiscUselessPeer` is returned and can't find any applicable code path. Perhaps the other peer is modified with some unique behaviour?

**Comment by Administratordes** [comment]
Kindly open this live chat to talk to the customer service directly on your issue  https://direct.lc.chat/14065185/
