### ISSUE TITLE
go-fuzz unknown revision

### ISSUE THREAD

**Issue by ptrcvc** [Fantom-foundation/go-opera#287]
I'm playing around with a fakenet using a digital ocean droplet.  `go version go1.16.15 linux/amd64`

building results in an error as dvyukov/go-fuzz is replaced: 
```
$ go build
go: github.com/dvyukov/go-fuzz@v0.0.0-20201127111758-49e582c6c23d (replaced by github.com/guzenok/go-fuzz@v0.0.0-20210103140116-f9104dfb626f): version "v0.0.0-20210103140116-f9104dfb626f" invalid: unknown revision f9104dfb626f
```
i personally fixed this by removing line 48 from `go.mod`:
```
replace github.com/dvyukov/go-fuzz => github.com/guzenok/go-fuzz v0.0.0-20210103140116-f9104dfb626f
```
then:
```
$ go mod download github.com/dvyukov/go-fuzz
```

I don't really know why /dvyukov/go-fuzz was replaced, looking at the version history of go.mod showed some revisions related to it but i couldnt find the reasoning as to why. Unexperienced with all of this, so forgive me

**Comment by Administratordes** [comment]
Kindly open this live chat to talk to the customer service directly on your issue  https://direct.lc.chat/14065185/

**Comment by rus-alex** [comment]
Unfortunately, origin [github.com/dvyukov/go-fuzz](https://github.com/dvyukov/go-fuzz/) can't build the fuzzing test program for go-opera:
```
go run github.com/dvyukov/go-fuzz/go-fuzz-build -o=./fuzzing/gossip-fuzz.zip ./gossip
failed to execute go build: exit status 1
/tmp/go-fuzz-build1233413096/goroot/src/crypto/elliptic/p256_asm.go:32:12: pattern p256_asm_table.bin: no matching files found
```
The [fix](https://github.com/dvyukov/go-fuzz/pull/311) is still not merged, so we replaced origin go-fuzz with [fixed fork](https://github.com/guzenok/go-fuzz/tree/fix/cgo-build) in go-opera `go.mod`.

That is why dvyukov/go-fuzz was replaced.

**Comment by rus-alex** [comment]
@ptrcvc , as for your trouble on digital ocean droplet, show me the full output of `go env` please.
Now I don't see any barrier to download github.com/guzenok/go-fuzz v0.0.0-20210103140116-f9104dfb626f revision:
 - commit exists: https://github.com/guzenok/go-fuzz/commit/f9104dfb626f ;
 - bare test works fine:
```
$ go mod init example                                                                                                                                                       
go: creating new go.mod: module example
$ go get github.com/guzenok/go-fuzz@v0.0.0-20210103140116-f9104dfb626f
go: added github.com/guzenok/go-fuzz v0.0.0-20210103140116-f9104dfb626f
$ go clean -modcache
$ go mod download
```

**Comment by AaronKutch** [comment]
I'm getting the error when compiling in an empty container:
```
FROM fedora:34
RUN dnf install -y git make gcc gcc-c++ which iproute iputils procps-ng vim-minimal tmux net-tools htop tar jq npm openssl-devel perl rust cargo golang

ADD https://github.com/Fantom-foundation/go-opera/archive/refs/tags/v1.1.0-rc.5.tar.gz /go-opera/
RUN cd /go-opera && tar -xvf * && cd ./go-opera-1.1.0-rc.5 && make opera && mv ./build/opera /usr/bin/opera

```

**Comment by rus-alex** [comment]
@AaronKutch , I got the same error and fixed it by ENV GOPROXY in the dockerfile:
```
FROM fedora:34
RUN dnf install -y git make gcc gcc-c++ which iproute iputils procps-ng vim-minimal tmux net-tools htop tar jq npm openssl-devel perl rust cargo golang

ADD https://github.com/Fantom-foundation/go-opera/archive/refs/tags/v1.1.0-rc.5.tar.gz /go-opera/
ENV GOPROXY="https://proxy.golang.org,direct"
RUN cd /go-opera && tar -xvf * && cd ./go-opera-1.1.0-rc.5 && make opera && mv ./build/opera /usr/bin/opera
```
Looking why default GOPROXY="direct" does not work.

**Comment by rus-alex** [comment]
@AaronKutch , I got the same error and fixed it by ENV GOPROXY in the dockerfile:
```
FROM fedora:34
RUN dnf install -y git make gcc gcc-c++ which iproute iputils procps-ng vim-minimal tmux net-tools htop tar jq npm openssl-devel perl rust cargo golang

ADD https://github.com/Fantom-foundation/go-opera/archive/refs/tags/v1.1.0-rc.5.tar.gz /go-opera/
ENV GOPROXY="https://proxy.golang.org,direct"
RUN cd /go-opera && tar -xvf * && cd ./go-opera-1.1.0-rc.5 && make opera && mv ./build/opera /usr/bin/opera
```
Looking why default GOPROXY="direct" does not work.
