### ISSUE TITLE
Transaction tracing returns incorrect results if transaction contains a revert

### ISSUE THREAD

**Issue by bsamuels453** [Fantom-foundation/go-opera#288]
**Describe the bug**
If a transaction contains a function-scoped revert, `trace_transaction` fails to calculate the output of the subtraces after the revert that are part of the same transaction. It also seems to be setting gasUsed to 0 for all traces after the revert. This issue applies to the other tracing calls as well. 

**To Reproduce**

Reference the following transaction which contains a function-scoped revert early in the execution: https://dashboard.tenderly.co/tx/fantom/0xa44fa1857fa5448419ff94682de1ffeccaa74eb0d6dc9d0de8fe37c6c2a90746

Construct an RPC query to obtain the transaction's traces. The go-opera version being tested against is `go-opera/v1.1.0-txtracing-rc.3-b7b34536-1645893046/linux-amd64/go1.17.7`
```
{
  "jsonrpc": "2.0",
  "method": "trace_transaction",
  "params": [
    "0xa44fa1857fa5448419ff94682de1ffeccaa74eb0d6dc9d0de8fe37c6c2a90746"
  ],
  "id": 1
}
```

The following trace is returned: https://gist.github.com/bsamuels453/2a36ed034a052a12993771454c4e2910

At trace address 3,0,0, the 3,0 subtrace is reverted: https://gist.github.com/bsamuels453/2a36ed034a052a12993771454c4e2910#file-tracing-result-json-L1090

For all of the traces afterwards (trace address 4 and later), `result.output` is not populated, and `result.gasUsed` is set to 0x0.

**Expected behavior**
Subtraces that occur after a revert should have their output/gasUsed fields populated as long as they aren't part of the specific subtrace that was reverted.

**Additional context**

**Comment by bsamuels453** [comment]
more reproduction instructions
---

here's an example contract that triggers the issue: https://gist.github.com/bsamuels453/07398f122a8f915f8fe0b2137050d2b2

I deployed the example contract here: https://ftmscan.com/address/0x2d819d1adb0b10154a5d90a36cb689b7bf786190#code
Here's a transaction I created that reverts, then has subsequent traces: https://ftmscan.com/tx/0x4692372dd695333556645ad68649c50db82acbe8efa7962c9ec94883752fb289

Here's the trace result from etherscan (same as the rpc-tracing node returns): https://ftmscan.com/vmtrace?txhash=0x4692372dd695333556645ad68649c50db82acbe8efa7962c9ec94883752fb289&type=parity#raw

From the etherscan trace, we can see that the final call to addOne shows up in the trace with no result field and gasUsed set to 0x0

**Comment by Administratordes** [comment]
Kindly open this live chat to talk to the customer service directly on your issue  https://direct.lc.chat/14065185/
