### ISSUE TITLE
how to identify validator

### ISSUE THREAD

**Issue by huahuayu** [Fantom-foundation/go-opera#289]
Hi, in ftmscan there's a list of validators https://ftmscan.com/validators I'd like to know how it is been done? Can I get enode id based on this?

Is there a map distribution of validators?

**Comment by quan8** [comment]
If you're interested to run a validator node, please see this guide:
https://docs.fantom.foundation/staking/how-to-run-a-validator-node

**Comment by huahuayu** [comment]
Hi @quan8 I want to find a way to identify the validator's location. So since there's a page https://ftmscan.com/validators that's why I ask, how do you do it?

**Comment by quan8** [comment]
It's simply not supported.
