### ISSUE TITLE
Compiling for Windows?

### ISSUE THREAD

**Issue by lonnietc** [Fantom-foundation/go-opera#293]
Hello,

I see that Fantom opera can be compiled for Linux, but can it also be compiled for Windows?
Thanks

**Comment by quan8** [comment]
Yes, it is being used in Windows for some projects.
Though we recommend to run on Linux.

**Comment by lonnietc** [comment]
Hello @quan8,

I was just wondering since I have been able to compile it on Linux (Ubuntu 20.04) and was going to try to compile it on Windows as it is mostly in Golang and should cross-compile, but you also have some C/C++ which probably means that it would need something like MSYS2 with MinGW64 to bet set up in order to compile as a guess.
