### ISSUE TITLE
EVM processing takes a long time when gas usage is high

### ISSUE THREAD

**Issue by yzhou61** [Fantom-foundation/go-opera#297]
**Describe the bug**
If a block consumes a high amount of gas (> 5m), the EVM processing time of the block increases dramatically.

**To Reproduce**
1. Run the node on mainnet
2. Wait for a block that consumes more than 10M gas.
3. Observe the EVM processing time (the "t" variable in the "New block" print on the console)

**Expected behavior**
I would expect the processing time of a block should be somewhat linear to the gas used.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version v1.1.0-rc.4

**Comment by quan8** [comment]
Please use 1.1.1-rc.2 and try again. 
We're going to have several other improvements in next releases in near future.

**Comment by yzhou61** [comment]
Using v1.1.1-rc2, the problem seems to have gotten worse. Now I'm seeing the node getting seemingly "stuck" for much longer, especially when the gas usage is above 10M in a block.

My hardware should not be the limiting factor. I have Ryzen 5950x with 128G memory, NVME drive.
