### ISSUE TITLE
WARN [05-04|21:15:37.052] Network upgrade 1.1.0 was activated. Current node version is 1.0.2. Please upgrade your node and re-sync the chain data.

### ISSUE THREAD

**Issue by kaber2** [Fantom-foundation/go-opera#299]
All my 16 nodes failed suddenly with the above message. Given that there is neither a 1.1.0 release here, nor any announcement of a mandatory upgrade, I just have to ask, WTF?

How about some proper procedures here. Not everyone hangs around in chat channels or whereever you might have announced this. On top of that, a proper release also seems to be the right thing to do, with a changelog that states that it's mandatory. Basically, what everyone else does.

**Comment by kaber2** [comment]
Not even a tag for the latest -rc5 release. You got to be shitting me.

**Comment by kaber2** [comment]
After going through various branches and commits for 20 minutes, it is still unclear which the required version/commit is, also no new snapshots have released, so besides the necessary upgrade, days of synchronization ahead.

Seriously guys, that level of incompetence might be acceptable for a student project, not for a decentralized system claiming to "deliver unparalleled [...] reliability". There is a clear centralization problem here, and it is you.

**Comment by quan8** [comment]
@kaber2 We have made many announcements and tweets for the upgrade.
Please follow our Discord chats and FantomFDN Twitter to keep you up to date.

**Comment by kaber2** [comment]
Sorry, this is not how you run a software project. I refer you to Ethereum, BSC, Polygon, Bitcoin, the Linux kernel, any well run software project.  This is the site where the code is managed and released, when you do breaking changes, you tag a release and put it into the changelog. Chats and Twitter is transient information, a changelog is not.

**Comment by quan8** [comment]
As said, if you are actually following Fantom, you should have known the announcements.
Please follow our Discord chats and FantomFDN Twitter to keep you up to date.
