### ISSUE TITLE
deploy official binary releases

### ISSUE THREAD

**Issue by AaronKutch** [Fantom-foundation/go-opera#301]
It appears to me that only the source code artifacts are released. For the purposes of local and automated tests (In particular I work with a Github Actions CI that needs the binary 15 times in parallel), it would be great if there were a container I could `COPY` from on Dockerhub or a `.tar.gz` file of the binary with Github tags or on the official website. A clean build from source requires about a gigabyte of dependencies.

**Comment by quan8** [comment]
Merged. Thanks.
