### ISSUE TITLE
How to run an Archive Node ?

### ISSUE THREAD

**Issue by singhsahilzeeve** [Fantom-foundation/go-opera#317]
I could not find the documentation to run an archive node.

**Comment by Viperoq** [comment]
Kindly open this live chat to talk to the customer service directly on your issue  https://direct.lc.chat/14157678/

**Comment by quan8** [comment]
@Viperoq  is a scammer. Delete his comment.

**Comment by quan8** [comment]
@singhsahilzeeve 
https://docs.fantom.foundation/node/run-a-read-only-node
If you will need more info, please join our Discord chats (go to our homepage https://fantom.foundation, and you will find a link to Discord).

**Comment by masayil** [comment]
opera runs in archive mode by default

**Comment by singhsahilzeeve** [comment]
> 

Okay. Can you please let me know what should i do to run a full node ?. And is this [https://github.com/Fantom-foundation/lachesis_launch/blob/master/docs/import-evm-history.sh](url) step required to run archive node ?.

**Comment by masayil** [comment]
> > 
> 
> Okay. Can you please let me know what should i do to run a full node ?. And is this [https://github.com/Fantom-foundation/lachesis_launch/blob/master/docs/import-evm-history.sh](url) step required to run archive node ?.

yes.But it takes  a long time to synchronize a full archive node from genesis. I suggest you to download the snapshot
https://docs.fantom.foundation/node/snapshot-download
This is my setup steps.
[fantom-startup.zip](https://github.com/Fantom-foundation/go-opera/files/8760043/fantom-startup.zip)

**Comment by uprendis** [comment]
Note: downloading a snapshot (which is a zipped copy of datadir) is not a trsutless way at all. You have to trust that datadir is correct
New genesis file format should be released in the near future. Once it's released, you will be able to download the archive genesis file (3.1TB) and apply it securely on local machine instead of syncing from scratch. It'll take a bit longer than via snapshot, but it would be trustless

**Comment by singhsahilzeeve** [comment]
Please help me in knowing steps to run a non-archive node for fantom.

**Comment by quan8** [comment]
Hi @singhsahilzeeve ,
You may check this guide:
 https://docs.fantom.foundation/node/run-a-read-only-node
 https://github.com/Fantom-foundation/lachesis_launch
