### ISSUE TITLE
upgrade opera: wrong version of genesis file, got=00010001, expected=00020001

### ISSUE THREAD

**Issue by huahuayu** [Fantom-foundation/go-opera#318]
## step0: get warning
```text
Network upgrade 1.1.0 was activated. Current node version is 1.0.2. Please upgrade your node and re-sync the chain data.
```

## step1: update go-operat version to 1.1.1 and restart
```text
wrong version of genesis file, got=00010001, expected=00020001
```

## step2: update genesis file
visit https://github.com/Fantom-foundation/lachesis_launch/blob/master/docs/genesis-files.md to check the genesis file, but which one should I download?

I tried to download https://opera.fantom.network/mainnet.g, thought it is the latest, but it is not, it's the same as my current one.

**Comment by uprendis** [comment]
Hello @huahuayu,
Any of genesis files for mainnet in https://github.com/Fantom-foundation/lachesis_launch/blob/master/docs/genesis-files.md will work, but each of them has different starting point and different amount of data. Normally you want highest starting point possible, but amount of data and syncing mode depend on your usecase
