### ISSUE TITLE
File Descriptor limit

### ISSUE THREAD

**Issue by Ostjimmy** [Fantom-foundation/go-opera#323]
I am not sure about this but I think there is File Descriptor limit in go-opera itself.

Other chain full nodes have over 266000, but Opera uses only around 2880.
I already maximized FD limit, but Opera still using only 2k.

It Looks like its node internal FD limit setting problem.
Please make --fdlimit option or set go-opera to use maximum setting.

**Comment by Ostjimmy** [comment]
There will be FD limit function on the next version.

**Comment by uprendis** [comment]
Hello @Ostjimmy,
Good day to you!
Yeah, we'll include it into a future version as a part of a larger optimization package

**Comment by quan8** [comment]
Hi @Ostjimmy , can you please try with new releases 1.1.2-rc.5 or 1.1.2-rc.6?
