### ISSUE TITLE
-txlookuplimit option

### ISSUE THREAD

**Issue by Ostjimmy** [Fantom-foundation/go-opera#324]
flag provided but not defined: -txlookuplimit
Its the error showing when I input Opera full node.

New GETH version has --txlookuplimit option. I don't know Opera's default setting, but we may need this option for Opera.

--txlookuplimit value
Number of recent blocks to maintain transactions index for (default = about one year, 0 = entire chain) (default: 2350000)

**Comment by uprendis** [comment]
Currently `opera` maintains indexing for all the newly processed blocks. Indexing for starting blocks depends on genesis file - it is possible to use genesis file with pruned blocks history

**Comment by Ostjimmy** [comment]
Thanks for your reply. I will close this issue.
