### ISSUE TITLE
why New block from index=4564026 point sync blockchain ,eventhough I downloaded the latest pruned snapshot ?

### ISSUE THREAD

**Issue by ai-chen2050** [Fantom-foundation/go-opera#332]
**Describe the bug**
why New block from index=4564026 point sync blockchain ,eventhough I downloaded the latest pruned snapshot ?

**To Reproduce**

**Expected behavior**

New block from the latest world state & syncing.

**Screenshots**
- The startup shell is follow:
```shell
opera --cache 64000 --genesis /data/fantom/mainnet.g --datadir /data/fantom/  --maxpeers 500 --nousb --http --http.addr '0.0.0.0' --http.port 8545 --http.corsdomain "*" --http.vhosts "*" --ws --ws.addr '0.0.0.0' --ws.port 8546  --ws.origins '0.0.0.0' --http.api "eth,debug,net,admin,web3,personal,txpool,ftm,dag" --ws.api "eth,debug,net,admin,web3,personal,txpool,ftm,dag" 
```

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/27693952/174531675-20091a20-a6b1-4ae5-8318-c99e1b885f03.png">

**Desktop (please complete the following information):**
 - OS: [AWS Linux]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hadv** [comment]
@ai-chen2050 I think it's normal if you downloaded and used this genesis file `mainnet-5577-pruned-mpt.g` 

Which genesis file did you use?

**Comment by ai-chen2050** [comment]
I use the official given genesis file: wget https://opera.fantom.network/mainnet.g
- where place download for mainnet-5577-pruned-mpt.g file?  Thx

**Comment by hadv** [comment]
> * where place download for mainnet-5577-pruned-mpt.g file?  Thx

You can download difference version of new genesis files from https://github.com/Fantom-foundation/lachesis_launch/blob/master/docs/genesis-files.md to use with the latest release of `opera`

**Comment by ai-chen2050** [comment]
I download pruned snapshot from (Daily (pruned) snapshot) https://ftmbootstraps.ultimatenodes.io/,  are you sure the right genesis file is mainnet-5577-pruned-mpt.g ?  whether I can not pointed the genesis file by --genesis (omit --genesis flag)

<img width="982" alt="image" src="https://user-images.githubusercontent.com/27693952/174570899-6a6f4288-2b22-4ab7-ae73-074b5a7ecf15.png">

**Comment by hadv** [comment]
> I download pruned snapshot from (Daily pruned snapshot) https://ftmbootstraps.ultimatenodes.io/, are you sure the right genesis file is mainnet-5577-pruned-mpt.g ? or mainnet-109331-pruned-mpt.g ? whether I can not pointed the genesis file by --genesis (omit --genesis flag)

If you already downloaded the snapshot of datadir then I think you don't need `--genesis` anymore

**Comment by uprendis** [comment]
Downloading datadir archives isn't secure, as you have to trust that archive is correct. Such an archive may contain a mistake (accidentally or intentionally)
In a case you're okay with pruned EVM, the fastest syncing mode is snapsync. Download [mainnet-109331-no-mpt.g](https://download.fantom.network/mainnet-109331-no-mpt.g) (58.3 GB) if you need full blocks history or [mainnet-109331-no-history.g](https://download.fantom.network/mainnet-109331-no-history.g) (16.3 KB) in a case if you're okay with blocks history only after block 37676547
Move or ease your current datadir, add `--syncmode snap` flag to enable snapsync, add `--genesis` flag with selected genesis file

**Comment by ai-chen2050** [comment]
> Downloading datadir archives isn't secure, as you have to trust that archive is correct. Such an archive may contain a mistake (accidentally or intentionally) In a case you're okay with pruned EVM, the fastest syncing mode is snapsync. Download [mainnet-109331-no-mpt.g](https://download.fantom.network/mainnet-109331-no-mpt.g) (58.3 GB) if you need full blocks history or [mainnet-109331-no-history.g](https://download.fantom.network/mainnet-109331-no-history.g) (16.3 KB) in a case if you're okay with blocks history only after block 37676547 Move or ease your current datadir, add `--syncmode snap` flag to enable snapsync, add `--genesis` flag with selected genesis file

some error happed, when I follow you steps.

Fatal: Failed to read genesis file: wrong version of genesis file, got=00020001, expected=00010001

**Comment by uprendis** [comment]
Please update `opera` to `v1.1.1-rc.1`

**Comment by quan8** [comment]
Hi @ai-chen2050 , is it still an issue?
