### ISSUE TITLE
Snapshots download is unavailable

### ISSUE THREAD

**Issue by 1doce8** [Fantom-foundation/go-opera#335]
Looks like snapshots on https://docs.fantom.foundation/node/snapshot-download are unavailable it returns 404

**Comment by uprendis** [comment]
Hello @1doce8,
Good day to you!
Using archived datadir isn't secure, as it involves a trust that the archive is correct
Instead of that, you may use customizable genesis files with or without snapsync (accessible since `1.1.1-rc.1`): https://github.com/Fantom-foundation/lachesis_launch
