### ISSUE TITLE
How to use config.toml for v1.1.1-rc.1?

### ISSUE THREAD

**Issue by Ten-Ou** [Fantom-foundation/go-opera#339]
After I use ./opera dumpconfig >> config.toml to create config.toml file, I want to start a fakenet network and use config.toml like ./opera --fakenet 1/1 --datadir data --config config .toml, but it cannot be started, and the following message is prompted:

Fatal: TOML config file error: config.toml, line 17: (p2p.Config.BootstrapNodes) EOF.
Use 'dumpconfig' command to get an example config file.
If node was recently upgraded and a previous network config file is used, then check updates for the config file.

How should it be solved? BootstrapNodesV5 = ["enr:"] Does this line need me to configure anything?

**Comment by hkalina** [comment]
You have a syntax error in your `config.toml` file - if you need more help, please attach the content of your config.toml file.
