### ISSUE TITLE
Full tracenode thinks it is fully synchronized when it is still 3 million blocks behind

### ISSUE THREAD

**Issue by michaelscheung** [Fantom-foundation/go-opera#355]
**Describe the bug**
I'm running a full tracenode, and it stop synchronizing before block 42 million (current block is almost 45 million). It then switches to doing LLR summaries and no longer synchronizes any new blocks. Restarting the program gets it to start synchronizing blocks temporarily, but it always switches to doing LLR summaries. I've tried leaving it running for 24 hours and it still does nothing but produce LLR summaries.

You can see in the below example that the last new block before the LLR summary is 41921985, but then the LLR summary has a last_block of 44813112. I also confirmed that `trace_block` does not work after block 41921985. `eth_getTransactionByHash` works, but the whole point of waiting a month for the tracenode to fully synchronize is for the `trace_*` RPC calls.
```
INFO [08-13|04:07:26.332] New block                                index=41921981 id=129704:3884:52c32c gas_used=5,844,800  txs=131/0 age=1mo10d21h t=76.028ms
INFO [08-13|04:07:26.371] New block                                index=41921982 id=129704:3898:696510 gas_used=1,592,110  txs=9/0   age=1mo10d21h t=38.830ms
INFO [08-13|04:07:26.416] New block                                index=41921983 id=129704:3914:2d3fa7 gas_used=4,252,273  txs=53/0  age=1mo10d21h t=45.167ms
INFO [08-13|04:07:26.503] New block                                index=41921984 id=129704:3924:5b7c01 gas_used=832,866    txs=15/0  age=1mo10d21h t=11.137ms
INFO [08-13|04:07:27.575] New block                                index=41921985 id=129704:3953:f60cae gas_used=22,963,355 txs=69/0  age=1mo10d21h t=1.069s
INFO [08-13|04:08:11.742] New LLR summary                          last_epoch=143391 last_block=44813112 new_evs=0  new_ers=0 new_bvs=44   new_brs=0 age=2m18.490s
INFO [08-13|04:08:11.742] New DAG summary                          new=3748 last_id=129704:3979:aac308 age=1mo10d21h t=6.555s
INFO [08-13|04:08:43.735] New LLR summary                          last_epoch=143391 last_block=44813240 new_evs=0  new_ers=0 new_bvs=344  new_brs=0 age=2m50.484s
INFO [08-13|04:10:18.743] New LLR summary                          last_epoch=143391 last_block=44813304 new_evs=0  new_ers=0 new_bvs=192  new_brs=0 age=4m25.492s
INFO [08-13|04:11:06.746] New LLR summary                          last_epoch=143391 last_block=44813368 new_evs=0  new_ers=0 new_bvs=192  new_brs=0 age=5m13.494s
```
...
```
INFO [08-13|09:01:55.750] New LLR summary                          last_epoch=143453 last_block=44827320 new_evs=0  new_ers=0 new_bvs=1206 new_brs=0 age=1m28.519s
INFO [08-13|09:04:31.369] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-13|09:10:16.760] New LLR summary                          last_epoch=143453 last_block=44827384 new_evs=0  new_ers=0 new_bvs=192  new_brs=0 age=9m49.528s
INFO [08-13|09:10:28.730] New LLR summary                          last_epoch=143453 last_block=44827528 new_evs=0  new_ers=0 new_bvs=624  new_brs=0 age=10m1.498s
INFO [08-13|09:11:18.772] New LLR summary                          last_epoch=143454 last_block=44827528 new_evs=1  new_ers=0 new_bvs=80   new_brs=0 age=10m51.540s
INFO [08-13|09:13:18.772] New LLR summary                          last_epoch=143455 last_block=44827528 new_evs=7  new_ers=1 new_bvs=0    new_brs=0 age=7m19.636s
INFO [08-13|09:18:36.843] New LLR summary                          last_epoch=143455 last_block=44827528 new_evs=3  new_ers=1 new_bvs=16   new_brs=0 age=5m31.533s
```

**To Reproduce**
These are the command line options I used: 
`
./go-opera/build/opera --datadir data --port 38080 --http --http.addr localhost --http.port 38081 --http.api eth,web3,net,ftm,sfc,trace,debug --ws --ws.addr localhost --ws.port 38082 --ws.api eth,web3,net,ftm,sfc,trace,debug --cache 32768 --maxpeers 30 --genesis mainnet-5577-full-mpt.g --nousb --syncmode full --tracenode --tracing
`

**Expected behavior**
The node should synchronize up to the current block and `trace_block` should work. Instead, it stops about 3 million blocks short and switches to doing LLR summaries. Even a synchronized node should still receive new blocks, as my non-tracing FTM node does.

**Desktop (please complete the following information):**
OS: `Linux version 5.15.0-43-generic (buildd@lcy02-amd64-026) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #46~20.04.1-Ubuntu SMP Thu Jul 14 15:20:17 UTC 2022`

FTM version:
```
./go-opera/build/opera version
Go-Opera
Version: 1.1.1-txtracing-rc.2
Git Commit: def1d2dc884ea16c2442a5b72b827e6bb84e4123
Git Commit Date: 1656249060
Architecture: amd64
Protocol Versions: [63]
Go Version: go1.18.1
Operating System: linux
GOPATH=/home/user/go
GOROOT=/home/user/.go
```

**Comment by quan8** [comment]
Hi @michaelscheung, it knows the data is 1mo10d21h old. You may just wait a bit. Synchronization speed also depends on connection speed and bandwidth. What type of SSD are you using, and how much IOPS? You may also increase maxpeers.

**Comment by michaelscheung** [comment]
I am running 8x 970 Evo Plus NVMe M.2 in RAID 0, with IOPs in the millions. I'm generally able to synchronize nodes faster than others. I don't think it's fair to say it knows the data is 1mo10d21h old. I can query for transactions (but not traces) that are only a few minutes old, which indicates that some part of the node thinks it is fully synchronized. The latest new block says the data is 1mo10d21h old, but then it proceeds to endlessly generate LLR summaries (for instance with `last_block=44813112` and `age=2m18.490s`) without importing any new blocks. I left it running for 24 hours and it still continued to generate LLR summaries with no new blocks. I've already synchronized several other phantom nodes and have never seen this behavior. In particular, they never stop importing new blocks for 24 hours+, either during synchronization or after being fully synchronized.

Furthermore, I don't think it explains why restarting the node temporarily alleviates the problem. In fact, that's the only way I've been able to make progress with synchronization - I restart the node whenever it gets stuck doing LLR summaries.

**Comment by HonzaDajc** [comment]
Hi @michaelscheung, can you please stop the node and delete `go-opera` directory inside your node datadir ( data/go-opera ) as this will purge the p2p connections and build a new ones after the node is started again. This will not touch the synchronized data. And if this will not help, please start the node with parameter `--verbosity=4` as this will print the debug information into the log, so we'll get more details about this state of the node.

**Comment by michaelscheung** [comment]
After repeatedly restarting the node whenever it got stuck generating LLR summaries, it eventually kept going. I'm not too far from full synchronization so I'll report back when it's fully synchronized or if I encounter the same issue. @HonzaDajc thanks for the tip, I'll try that if it happens again.

**Comment by michaelscheung** [comment]
Almost fully synchronized and I haven't encountered the issue again yet

**Comment by michaelscheung** [comment]
Update: I have yet to encounter the issue again. It seems to be a flaky issue that will probably be difficult to reproduce. So it's definitely something to look out for, but because I cannot reproduce the issue, I will close this. Thank you for your feedback.
