### ISSUE TITLE
Running in snap node, but the height stops at the snap height

### ISSUE THREAD

**Issue by PPianAIC** [Fantom-foundation/go-opera#362]
Running in snap node, but the height stops at the snap height. I don't know how to keep syncing

INFO [09-05|02:37:32.989] New LLR summary                          last_epoch=150576 last_block=46377882 new_evs=0    new_ers=0   new_bvs=0     new_brs=5    age=4m11.025s
INFO [09-05|02:37:36.875] Generating state snapshot                root=e796b5..25cc43 in=bd3e01..36ee91 at=42c670..9d8bb8 accounts=1,736,819 slots=135,230,953 storage=9.40GiB    elapsed=45h29m24.204s eta=16h2m50.067s
INFO [09-05|02:37:41.000] New LLR summary                          last_epoch=150576 last_block=46377882 new_evs=0    new_ers=0   new_bvs=0     new_brs=13   age=4m19.035s
INFO [09-05|02:37:44.885] Generating state snapshot                root=e796b5..25cc43 in=bd3e01..36ee91 at=430bf6..e78a80 accounts=1,736,819 slots=135,231,966 storage=9.40GiB    elapsed=45h29m32.213s eta=16h2m52.892s
INFO [09-05|02:37:50.935] New LLR summary                          last_epoch=150576 last_block=46377882 new_evs=0    new_ers=0   new_bvs=0     new_brs=6    age=4m28.970s
INFO [09-05|02:37:52.889] Generating state snapshot                root=e796b5..25cc43 in=bd3e01..36ee91 at=4354ea..26bdd7 accounts=1,736,819 slots=135,233,072 storage=9.40GiB    elapsed=45h29m40.217s eta=16h2m55.716s
INFO [09-05|02:37:58.968] New LLR summary                          last_epoch=150576 last_block=46377882 new_evs=0    new_ers=0   new_bvs=0     new_brs=5    age=4m37.003s
INFO [09-05|02:38:00.891] Generating state snapshot                root=e796b5..25cc43 in=bd3e01..36ee91 at=439fe1..72822d accounts=1,736,819 slots=135,234,173 storage=9.40GiB    elapsed=45h29m48.219s eta=16h2m58.539s
INFO [09-05|02:38:07.632] New LLR summary                          last_epoch=150576 last_block=46377882 new_evs=0    new_ers=0   new_bvs=0     new_brs=8    age=4m45.667s
INFO [09-05|02:38:08.906] Generating state snapshot                root=e796b5..25cc43 in=bd3e01..36ee91 at=43d668..13f1fd accounts=1,736,819 slots=135,234,973 storage=9.40GiB    elapsed=45h29m56.234s eta=16h3m1.366s
INFO [09-05|02:38:15.984] New LLR summary                          last_epoch=150576 last_block=46377882 new_evs=0    new_ers=0   new_bvs=0     new_brs=13   age=4m54.020s
INFO [09-05|02:38:16.907] Generating state snapshot                root=e796b5..25cc43 in=bd3e01..36ee91 at=444846..12a22e accounts=1,736,819 slots=135,236,648 storage=9.40GiB    elapsed=45h30m4.235s  eta=16h3m4.189s

> ftm.syncing
{
  currentBlock: 37676547,
  currentBlockHash: "0x0001ab120000187fd8069d3a4f6501d48ad4800778f40a76d79cf02469272a43",
  currentBlockTime: "0x16ec7a4b9a82ebfe",
  currentEpoch: "0x1ab13",
  highestBlock: 46378344,
  highestEpoch: "0x24c30",
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 0
}

**Comment by hadv** [comment]
Hi @PPianAIC ,

As you can saw in the output log `INFO [09-05|02:38:16.907] Generating state snapshot ...`, that mean node is still in progress of generating snapshot, it will continue syncing with the chain after snapshot was generated

**Comment by PPianAIC** [comment]
I want to know what snapshot it generates, because it has been generated all the time, and I don't know when it ends @hadv

**Comment by hadv** [comment]
> I want to know what snapshot it generates, because it has been generated all the time, and I don't know when it ends @hadv

You can check the `eta=16h3m4.189s` on the output log

**Comment by PPianAIC** [comment]
Ok, thanks. I'll wait

**Comment by AlexAkulov** [comment]
I faced with the same issue. 
I've started go-opera with mainnet-109331-full-mpt.g (3TB) snapshot. Gradually, the block in the log reached the actual value, but currentBlock value in ftm.syncing does not change at all.
```
{
  currentBlock: 37676547,
  currentBlockHash: "0x0001ab120000187fd8069d3a4f6501d48ad4800778f40a76d79cf02469272a43",
  currentBlockTime: "0x16ec7a4b9a82ebfe",
  currentEpoch: "0x1ab13",
  highestBlock: 56149755,
  highestEpoch: "0x2ef1b",
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 0
}
```
I've been waiting for 9 days but eta value doesn't change or increased. 

```
INFO [02-20|07:27:39.804] Generating state snapshot                root=e796b5..25cc43 in=7dd00d..02329c at=4ab33e..269e86 accounts=1,154,170 slots=91,716,345 storage=6.37GiB    elapsed=198h8m11.113s   eta=205h1m32.643s
INFO [02-20|07:27:42.900] New LLR summary                          last_epoch=192279 last_block=56148544 new_evs=0     new_ers=0    new_bvs=350    new_brs=13   age=30m32.799s
INFO [02-20|07:27:47.806] Generating state snapshot                root=e796b5..25cc43 in=7dd00d..02329c at=4ab55e..e346b0 accounts=1,154,170 slots=91,717,373 storage=6.37GiB    elapsed=198h8m19.115s   eta=205h1m40.924s
INFO [02-20|07:27:50.964] New LLR summary                          last_epoch=192279 last_block=56148544 new_evs=0     new_ers=0    new_bvs=200    new_brs=23   age=30m40.865s
INFO [02-20|07:27:55.818] Generating state snapshot                root=e796b5..25cc43 in=7dd00d..02329c at=4ab780..0beb20 accounts=1,154,170 slots=91,718,400 storage=6.37GiB    elapsed=198h8m27.127s   eta=205h1m49.214s
INFO [02-20|07:27:58.970] New LLR summary                          last_epoch=192279 last_block=56148544 new_evs=0     new_ers=0    new_bvs=250    new_brs=12   age=30m48.871s
INFO [02-20|07:28:03.820] Generating state snapshot                root=e796b5..25cc43 in=7dd00d..02329c at=4ab9b7..2153ef accounts=1,154,170 slots=91,719,421 storage=6.37GiB    elapsed=198h8m35.129s   eta=205h1m57.494s
INFO [02-20|07:28:07.024] New LLR summary                          last_epoch=192279 last_block=56148544 new_evs=0     new_ers=0    new_bvs=350    new_brs=27   age=30m56.925s
INFO [02-20|07:28:11.825] Generating state snapshot                root=e796b5..25cc43 in=7dd00d..02329c at=4abbfe..f87435 accounts=1,154,170 slots=91,720,457 storage=6.37GiB    elapsed=198h8m43.134s   eta=205h2m5.778s
INFO [02-20|07:28:15.798] New LLR summary                          last_epoch=192279 last_block=56148544 new_evs=0     new_ers=0    new_bvs=200    new_brs=12   age=31m5.699s
INFO [02-20|07:28:19.827] Generating state snapshot                root=e796b5..25cc43 in=7dd00d..02329c at=4abe37..18c6bf accounts=1,154,170 slots=91,721,524 storage=6.37GiB    elapsed=198h8m51.136s   eta=205h2m14.058s
```

It looks like bug in go-opera. My previous syncs on older versions didn't behave this way.

**Comment by quan8** [comment]
Hi @AlexAkulov , the above logs are expected. Snapsync may take 8+ hours to finish syncing. When it's finished, you will see "New block" in the log as usual. Please make sure to use our latest opera version and check your machine specs. For further support, please use Discord.
