### ISSUE TITLE
callTracer execution timeout before specified timeout value

### ISSUE THREAD

**Issue by quickchase** [Fantom-foundation/go-opera#369]
**Describe the bug**
The timeout value for debug_traceBlockByNumber is not being honored.

**To Reproduce**
Running `go-opera/v1.1.1-txtracing-rc.2-def1d2dc-1656249060`

```
time curl -s -H 'Content-Type; application/json' -d '{
  "jsonrpc": "2.0",
  "method": "debug_traceBlockByNumber",
  "params": ["0x2ba8032", { "tracer": "callTracer", "timeout": "1h" }],
  "id": 1666
}' http://localhost:8545 | jq '.'

<redacted output>

    {
      "error": "execution timeout"
    },
    {
      "error": "execution timeout"
    }
  ]
}

0.05s user 0.01s system 0% cpu 10.164 total
```

**Expected behavior**
I expect never to receive the error `execution timeout` prior to the `timeout` value I have specified in the tracer.

**Additional Information**
I did check to see if there was a configurable value like `--rpc.evmtimeout` but could not find any way to override this behavior.

**Comment by cp0k** [comment]
Hoping someone has an update for this one, thanks!

**Comment by cattingcat** [comment]
It'd be really great to fix it

**Comment by cp0k** [comment]
Happy New Year bump :)

**Comment by qk-santi** [comment]
Solved by https://github.com/Fantom-foundation/go-opera/pull/393
