### ISSUE TITLE
Can't download snapshots from download1.fantom.network

### ISSUE THREAD

**Issue by voltagebots** [Fantom-foundation/go-opera#370]
**Describe the bug**

I'm unable to download latest non-pruned datadir snapshots. `https://download1.fantom.network/snap/opera_6june22.tgz`
It appears `download1.fantom.network `is down

**To Reproduce**
try downloading a snapshot - 
`wget https://download1.fantom.network/snap/opera_6june22.tgz`

**Comment by quan8** [comment]
Snapshots available at: https://docs.fantom.foundation/node/snapshot-download
