### ISSUE TITLE
Old SFC transactions return wrong traces

### ISSUE THREAD

**Issue by jpitb** [Fantom-foundation/go-opera#372]
**Describe the bug**
When you call debug_traceBlockByNumber for blocks with transactions that interacted with an older version of SFC you get a "reverted" when it is not true.

**To Reproduce**
1. Query debug_traceBlockByNumber for block 157341
2. You get
`{"jsonrpc":"2.0","id":157341,"result":[{"action":{"from":"0x0000000000000000000000000000000000000000","to":"0xfc00face00000000000000000000000000000000","value":"0x0","gas":"0x0"},"blockHash":"0x0000043a00001a905a371232ffec659856bedaaeae1c2d7f57ea7e617912fbf1","blockNumber":157341,"error":"Reverted","subtraces":0,"traceAddress":[],"transactionHash":"0x2afc5d27edea07edc4972422cef5560b0a2c54ee706bf1c921050ac77bd56b9d","transactionPosition":0,"type":"empty"}]}`
You can check the output also here: https://ftmscan.com/vmtrace?txhash=0x2afc5d27edea07edc4972422cef5560b0a2c54ee706bf1c921050ac77bd56b9d&type=parity
4. Check the only tx from that block https://ftmscan.com/txs?block=157341 and you will see that it has a SUCCESS status and it did change balances

**Expected behavior**
The traces for the FTM transfers are expected to be returned

**Additional context**
This issues makes impossible to build any analytical product for Fantom as you can not compute accurate addresses balances with the data extracted from the RPCs. 

Just one of many examples with addresses with negative balances at some point in time
https://ftmscan.com/address/0xa278c694955ad9e4249ef72baaabbcbfaaf291c6#analytics

**Comment by quan8** [comment]
Hi @jpitb , please use latest SFC version and latest opera tracing version.

**Comment by Buyzed** [comment]
372
