### ISSUE TITLE
Supporting a "finalized" parameter for `eth_getBlockByNumber`

### ISSUE THREAD

**Issue by AaronKutch** [Fantom-foundation/go-opera#374]
Previously, our bridges used the "latest" parameter minus a set number of blocks in order to determine when a block could be relayed as unreorganizable. Since Eth 2.0 a "finalized" parameter has been supported by many chains, and we want to use more concrete proof-of-stake guarantees instead of probabilistic assumption guarantees. It appears that go-opera does not support this. Regardless if there is already some custom endpoint for this, could it also be exposed through the standard eth_getBlockByNumber so that we do not have to make `go-opera`-specific changes to our backend libraries?

**Comment by quan8** [comment]
@AaronKutch Once a block is confirmed, it's finalized in Fantom.
