### ISSUE TITLE
Missing trie node on non archive node

### ISSUE THREAD

**Issue by soltrac** [Fantom-foundation/go-opera#375]
**Is your feature request related to a problem? Please describe.**
In normal GETH, we can see info about the last 128 blocks, we can ask the node for some data of previous blocks even if we don't have an archive node.

But I'm not sure if we have anything similar in go-opera. I'm receiving missing trie node in nodes back several seconds behind. I suppose we have also 128 blocks, but maybe is not enough because blocks in go-opera are very fast

**Describe the solution you'd like**
I would like to know if there is a parameter or something like that in go-opera that maybe we can add more blocks to keep indexed.

**Comment by quan8** [comment]
@soltrac  If pruning (either offline or using gcmode) is not used, then the data is retained.
Which command did you use to run your node? It's recommended to run using SSD, NVMe SSD, and good internet connection.

**Comment by soltrac** [comment]
I'm using --gcmode light, so that's the problem. It is possible to define how many "last blocks" to leave before automatic pruning?

**Comment by hadv** [comment]
> I'm using --gcmode light, so that's the problem. It is possible to define how many "last blocks" to leave before automatic pruning?

currently, opera keeps the last 16 blocks' state. Expose this into config is a good idea I think

**Comment by soltrac** [comment]
> > I'm using --gcmode light, so that's the problem. It is possible to define how many "last blocks" to leave before automatic pruning?
> 
> currently, opera keeps the last 16 blocks' state. Expose this into config is a good idea I think

That would be great, anyway where can I find in the source code those 16 last block states? I've been trying to find it but no success

**Comment by hadv** [comment]
> 
> That would be great, anyway where can I find in the source code those 16 last block states? I've been trying to find it but no success

You can find it here https://github.com/Fantom-foundation/go-opera/blob/884fa842c628abae7af4bf816de6045eba9bd725/gossip/evmstore/store.go#L63

**Comment by soltrac** [comment]
Thank you!!!, I close this then
