### ISSUE TITLE
Which genesis file should I use?

### ISSUE THREAD

**Issue by zhaoxiangjunupi** [Fantom-foundation/go-opera#379]
I am using the snapshot synchronization method.
Which genesis file should I use?
![image](https://user-images.githubusercontent.com/101166067/196899390-b9e5c858-9769-41d4-918c-dd42295abec3.png)

**Comment by quan8** [comment]
Hi @zhaoxiangjunupi , Depending on what your node will be used for. 
- For API node (full history), full* can be used. If full history is not required, use pruned*.
- For Read node (not validator), full* and pruned* can be used. Also snapsync can be used.
- For validator node, use full* or pruned*.

**Comment by zhaoxiangjunupi** [comment]
> 

For snapshot-synchronized read nodes, do you mean these two?
![image](https://user-images.githubusercontent.com/101166067/196904793-dbd7461b-af2c-4283-86a7-f5d7dc0942bb.png)
