### ISSUE TITLE
why no log is printed？

### ISSUE THREAD

**Issue by zhaoxiangjunupi** [Fantom-foundation/go-opera#380]
I created a read-only node using snapshot synchronization, but why did it not print the log when it started, does it have to wait for a while?

**Comment by quan8** [comment]
Hi @zhaoxiangjunupi , please use Fantom discord for further support questions.

**Comment by zhaoxiangjunupi** [comment]
> 

Dockerfile:
![image](https://user-images.githubusercontent.com/101166067/197095991-60b3445a-b1b8-4ff9-bbb9-b41a0cffe3a6.png)
entrypoint.sh:
![image](https://user-images.githubusercontent.com/101166067/197096091-8db109ef-5144-4e0f-9d12-779c2b8b9cc4.png)
run.sh:
![image](https://user-images.githubusercontent.com/101166067/197096387-079b4cc7-79f4-4703-a195-8bb75d6699c6.png)

**Comment by zhaoxiangjunupi** [comment]
> Hi @zhaoxiangjunupi , please use Fantom discord for further support questions.

No one answered me there, please find someone to answer me

**Comment by hadv** [comment]
@zhaoxiangjunupi if you set `--verbosity=2` then only ERROR and WARN log level was output. Can you try to set it to 3 then INFO log will be print out!

**Comment by zhaoxiangjunupi** [comment]
> @zhaoxiangjunupi if you set `--verbosity=2` then only ERROR and WARN log level was output. Can you try to set it to 3 then INFO log will be print out!

ok thank you, i will give it a try
