### ISSUE TITLE
why CRIT [10-26|10:06:07.332] Failed to migrate Gossip DB              module=gossip-store err="unknown version: 5a210b63734035490d63560007b4e60e3f52461b496e62eeb4c6c4c0959e457d"

### ISSUE THREAD

**Issue by zhaoxiangjunupi** [Fantom-foundation/go-opera#381]

**Comment by zhaoxiangjunupi** [comment]
CRIT [10-26|10:06:07.332] Failed to migrate Gossip DB              module=gossip-store err="unknown version: 5a210b63734035490d63560007b4e60e3f52461b496e62eeb4c6c4c0959e457d"

**Comment by zhaoxiangjunupi** [comment]
Excuse me, what's the situation?

**Comment by sonderangebot10** [comment]
I am getting the same error

**Comment by sonderangebot10** [comment]
@zhaoxiangjunupi did you manage to resolve it?

**Comment by quan8** [comment]
@zhaoxiangjunupi  which go-opera version did you use? Any new github issue should give enough info for reproduction.
