### ISSUE TITLE
What's wrong with this？

### ISSUE THREAD

**Issue by zhaoxiangjunupi** [Fantom-foundation/go-opera#383]
![image](https://user-images.githubusercontent.com/101166067/198976208-ab3e6b77-c5c1-4508-ac38-e9e750f43e8d.png)

**Comment by zhaoxiangjunupi** [comment]
What's wrong with this？

**Comment by hadv** [comment]
> What's wrong with this？

@zhaoxiangjunupi state heal progress is one the steps in the **snapsync** so I think it's not any issue. Please wait a bit more time for it to complete.

**Comment by zhaoxiangjunupi** [comment]
> > What's wrong with this？
> 
> @zhaoxiangjunupi state heal progress is one the steps in the **snapsync** so I think it's not any issue. Please wait a bit more time for it to complete.

thank you。
