### ISSUE TITLE
Cannot get a node to run

### ISSUE THREAD

**Issue by sonderangebot10** [Fantom-foundation/go-opera#386]
Hi!

I just downloaded a fresh pruned snapshot, as well as a genesis file. However when I run opera I get the following error:
`CRIT [10-26|10:06:07.332] Failed to migrate Gossip DB module=gossip-store err="unknown version: 5a210b63734035490d63560007b4e60e3f52461b496e62eeb4c6c4c0959e457d"`

Just can't get it to work.. Any ideas?

**Comment by quan8** [comment]
Hi @sonderangebot10 , which version of go-opera and the command are you using?

**Comment by sonderangebot10** [comment]
@quan8 I am using Version: 1.1.1-rc.1 and my command is
`./opera --datadir /node/data --genesis /node/mainnet.g`

**Comment by quan8** [comment]
Hi @sonderangebot10 , 
Please use  1.1.1-rc.2. This guide may help https://docs.fantom.foundation/node/run-a-read-only-node
