### ISSUE TITLE
Unable to sync, node keeps lagging behind

### ISSUE THREAD

**Issue by dsbrgg** [Fantom-foundation/go-opera#392]
**Describe the bug**

I had a running API node for Fantom but wanted to change my architecture for nodes that were running. I've reused the data I was using on an AWS node to this new setup and had an issue with `dirty state` but solved by using the `fixdirty` API provided by the node. It seemed to be catching up rather normally but after some time, the node got really slow up to a point that start simply to lag behind when it was roughly 8 days behind of a complete sync (now it's 10 days behind).

**To Reproduce**

As I mentioned, I've just reutilized an EBS volume that was storing all the node data to this new setup. I guess the main difference is that the older setup was running an older version of the node and now it's running the LTS.

**Expected behavior**

The node should sync normally.

**Screenshots**

![image 2](https://user-images.githubusercontent.com/25888358/203077381-6d89f912-7370-43c0-8453-d938bb794706.jpeg)
![image](https://user-images.githubusercontent.com/25888358/203077398-217bb498-f71a-4041-b138-f0cf583e3fd1.jpeg)

**Desktop (please complete the following information):**
 - Version: `go-opera v1.1.1-rc.2`

**Comment by uprendis** [comment]
Hello @dsbrgg,
Good day to you!
There's going to be an upcoming release soon which will greatly improve the performance

**Comment by dsbrgg** [comment]
So is this strictly a performance issue? Like I mentioned, after some time it was actually lagging and not being able to catch up properly. Is there any sort of approach to take? I've tried many different ones from simply restarting multiple times, remving `go-opera` folder to fetch peers again, toggling between `full` and `snap` on `syncmode`... I wonder if somebody had a similar issue, with previous versions of the node I never had this problem.

**Comment by dsbrgg** [comment]
Sorry to insist on this but I've tried a differrent method: 
- Use my own snapshot again for a running node but with a downgraded version of the node (`1.1.1-rc.1` instead of `1.1.1-rc.2`)

And still, it took 3 days of `Generate state snapshot` logs and now it seems to be syncing but in a very slow pace, actually lagging behind as well.

I have one other node running this same version (`1.1.1-rc.1`)  without issues. The only difference is that when I ran with this state snapshot, I had to run `opera fixdirty` in order to fix db inconsistencies (although I know the API is experimental).

Is there any directives for this kind of situation?

**Comment by dsbrgg** [comment]
@quan8 
is there an issue with the network or this latest release? I've tried a fresh start with the node using the full history latest snapshot. It started normally (without having to run `fixdirty`) as a read node, but it keeps lagging behind still. I know for sure that it's not an issue with my current specs. As I explained above, I've tried different approaches and all of them ended up having the same issue, regardless which snapshot is from (mine or the ones Fantom provides) or the release. 

The other node running at `1.1.1-rc.1` was also upgraded to that from `1.1.0-rc.3` if I'm not mistaken and it still is running smoothly, even after stopping it, it never has an issue to catch up.

What I can tell is that the nodes I'm trying to use get up to speed never show the `age` with more detailed information always with a short format instead of for example `age=1h36m29.546s`. In their case its always `age=1h36m29s`. I know this might not be useful information but it was the difference I was able to see between both cases where one actually syncs and the other lags behind.

**Comment by dev-anshu** [comment]
`root@ip-172-31-43-188:/home/ubuntu/go-opera/build# ./opera fixdirty
INFO [12-19|18:00:23.412] Maximum peer count                       total=50
INFO [12-19|18:00:23.413] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [12-19|18:00:23.413] Opening databases 
CRIT [12-19|18:00:23.413] DB opening error                         datadir=/root/.opera err="resource temporarily unavailable"
root@ip-172-31-43-188:/home/ubuntu/go-opera/build# 
`
i am getting this error after restarting the node syncing. Mine node syncing was also running behind. It was just giving LLR summary of last block but the ./opera attach --exec ftm.blockNumber giving me same blocknumber from past 2 days.

**Comment by quan8** [comment]
Hi @dsbrgg ,  what is the specs of the server? what is IOPS?
Btw, you may try with our latest release.

Please join our discord and our support will help you there.
