### ISSUE TITLE
Snapshot opera-full_14-Nov-2022-13-16 removed

### ISSUE THREAD

**Issue by dsbrgg** [Fantom-foundation/go-opera#394]
**Describe the bug**

I was downloading snapshot `opera-full_14-Nov-2022-13-16.tar.gz` and it literally got removed from the server mid-download and it is a pretty big download, I would expect some kind of announcement that these would be pruned (which I could have missed it).

**To Reproduce**

You can use `wget` or `curl` but I was using `aria2c` in this case:

```
aria2c -s 5 https://snapshot1.fantom.network/files/snapshot-14-Nov-2022-13-16/opera-full_14-Nov-2022-13-16.tar.gz

11/28 22:56:51 [NOTICE] Downloading 1 item(s)

11/28 22:56:52 [ERROR] CUID#7 - Download aborted. URI=https://snapshot1.fantom.network/files/snapshot-14-Nov-2022-13-16/opera-full_14-Nov-2022-13-16.tar.gz
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://snapshot1.fantom.network/files/snapshot-14-Nov-2022-13-16/opera-full_14-Nov-2022-13-16.tar.gz
  -> [HttpSkipResponseCommand.cc:219] errorCode=3 Resource not found
  ```

**Expected behavior**

The resource is there.

**Screenshots**

![Screenshot 2022-11-28 at 22 58 32](https://user-images.githubusercontent.com/25888358/204398520-10eb6902-5dd4-4ced-8f11-5a6b9fd7bfcb.png)

**Comment by quan8** [comment]
There is a new version of the snapshot. Due to resource limitation (each tar is in TBs), we can't keep all the versions.
