### ISSUE TITLE
My node cannot broadcast the transaction

### ISSUE THREAD

**Issue by julycanfly** [Fantom-foundation/go-opera#409]
Originally the node is normal, since yesterday suddenly appeared this problem.When I broadcast the transaction, returned the known error.But when I broadcast the transaction over a public node, it succeeds.
request:
```
curl --location --request POST 'http://127.0.0.1:9884' \
--header 'Content-Type: application/json' \
--data '{
    "id": 0,
    "jsonrpc": "2.0",
    "method": "eth_sendRawTransaction",
    "params": ["0xf86f80853edd410c0082c350945bdf85216ec1e38d6458c870992a69e38e03f7ef8905a31a42ce5028400080820218a070c67d3b69786d2bbe8df9570519c46ddebbce25b02fe5e9f9b522205e31598ea026d29cbad74eacc29d359ad529bb8e6febedf54ee8fdbcec2a44d44"]
    }'
```
response:
{"jsonrpc":"2.0","id":0,"error":{"code":-32000,"message":"already known"}}

**Comment by quan8** [comment]
Hi @leezijie , does the issue still persist? could it be a hardware or connectivity issue?
