### ISSUE TITLE
Go-Opera Version: 1.1.2-txtracing-rc.2  full-node takes up a lot of disk space

### ISSUE THREAD

**Issue by zhy827827** [Fantom-foundation/go-opera#411]
hi,
i update Go-Opera to 1.1.2-txtracing-rc.2. After running for two days, I found a problem: the disk space grew very fast,add 1T more disks a day
My configuration is:
/home/ubuntu/go-opera/build/opera --genesis /opt/rockx/data/mainnet.g-5577 --tracenode --db.migration.mode reformat --db.preset=legacy-ldb --syncmode full --gcmode full --http --http.addr 0.0.0.0 --http.vhosts=* --http.api=eth,web3,net,ftm,sfc,trace --http.corsdomain=* --ws --ws.origins=* --datadir /opt/rockx/data/.opera --maxpeers 100

Go-Opera to 1.1.1-txtracing-rc.2 full-node use disk 3T
but Go-Opera to 1.1.2-txtracing-rc.2 full-node user disk 5T+

Does anyone have the same problem?

**Comment by hadv** [comment]
Hi @zhy827827,

there's an issue of leveldb on `txtracing/1.1.2-rc.2` that make diskspace issue. You can use `txtracing/1.1.2-rc.5` instead

https://github.com/Fantom-foundation/go-opera/tree/release/txtracing/1.1.2-rc.5

**Comment by quan8** [comment]
Hi @zhy827827 , please use our latest release.
