### ISSUE TITLE
Invalid character dash in Prometheus metric names

### ISSUE THREAD

**Issue by Maharacha** [Fantom-foundation/go-opera#415]
**Describe the bug**
There are metrics in the Prometheus endpoint with the invalid character dash. Example: `opera_chaindata_gossip-17275_disk_size`.
Prometheus interface will complain with `invalid metric type "17275_disk_size gauge"`.

**To Reproduce**
Run txtracing binary from https://github.com/Fantom-foundation/go-opera/tree/release/txtracing/1.1.1-rc.2
Enable metrics and use Prometheus to scrape it at path `/debug/metrics/prometheus`.

**Expected behavior**
Prometheus able to scrape the metrics.

**Comment by hadv** [comment]
@Maharacha should be fixed by #418 Can you try it please? Thanks!

**Comment by Maharacha** [comment]
> @Maharacha should be fixed by #418 Can you try it please? Thanks!

Seems to work! Will you take it to txtracing as well? I'm not familiar with the workflow in this repo..

**Comment by Maharacha** [comment]
> > @Maharacha should be fixed by #418 Can you try it please? Thanks!
> 
> Seems to work! Will you take it to txtracing as well? I'm not familiar with the workflow in this repo..

But I'm not sure, because I did not have this problem when running without `txtracing`.

**Comment by Maharacha** [comment]
> > > @Maharacha should be fixed by #418 Can you try it please? Thanks!
> > 
> > 
> > Seems to work! Will you take it to txtracing as well? I'm not familiar with the workflow in this repo..
> 
> But I'm not sure, because I did not have this problem when running without `txtracing`.

My bad, I just realized that I was running an older version when running without txtracing and that's probably why I did not have the problem. Anyway, please take it to txtracing as well and I will be very happy :smile:

**Comment by Maharacha** [comment]
I cherry-picked your fix to txtracing on our [fork](https://github.com/dwellir-public/go-opera/releases/tag/v1.1.2-rc.2-prometheus-fix) and it's working like a charm, thanks!

**Comment by hadv** [comment]
> I cherry-picked your fix to txtracing on our [fork](https://github.com/dwellir-public/go-opera/releases/tag/v1.1.2-rc.2-prometheus-fix) and it's working like a charm, thanks!

okay, I also back port and will release in new version of txtracing on #419

**Comment by quan8** [comment]
Temporary patches. 
https://github.com/Fantom-foundation/go-opera/pull/450
https://github.com/Fantom-foundation/go-opera/pull/451
(Not to be merged into those branches but will release a new branch)
