### ISSUE TITLE
transaction failed but trace_block doesn't report that

### ISSUE THREAD

**Issue by quick-pawiromitchel** [Fantom-foundation/go-opera#416]
**Describe the bug**
This [transaction](https://ftmscan.com/tx/0x61f31016183085cf922364854eb21b308b5cdd3189482a5797a9b09367419ec3) shows up as `Fail` on FTMScan, but the response from `trace_block` doesn't indicate that.

**To Reproduce**
1. compare the output from `{ "method": "debug_traceTransaction", "params": [ "0x61f31016183085cf922364854eb21b308b5cdd3189482a5797a9b09367419ec3", { "tracer": "callTracer" } ], "id": 1, "jsonrpc": "2.0" }`
2. with `{ "method": "trace_block", "params": [ "0x33795D9" ], "id": 1, "jsonrpc": "2.0" }` and search for `0x61f31016183085cf922364854eb21b308b5cdd3189482a5797a9b09367419ec3`

**Expected behavior**
Both responses should be the same or indicate the same, that the tx is out of gas

**Screenshots**
`debug_traceTransaction`
![CleanShot 2023-01-18 at 08 06 09](https://user-images.githubusercontent.com/103942361/213155924-a27ceeff-9b99-4f01-9e04-70876c3bacb5.png)

`trace_block`
![CleanShot 2023-01-18 at 08 06 20](https://user-images.githubusercontent.com/103942361/213155972-9760509c-8c58-4b88-af2d-95916fa82838.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1
 - Version `1.1.1-txtracing-rc.2-0b72c064-1662050628`

**Comment by jenikd** [comment]
Hi @quick-pawiromitchel, thanks for reporting this bug. It will be fixed in next release candidate

**Comment by quick-pawiromitchel** [comment]
Awesome, thank you!
