### ISSUE TITLE
run opera error with ' failed to open existing databases: resource temporarily unavailable'

### ISSUE THREAD

**Issue by past2017** [Fantom-foundation/go-opera#423]
~# ls /data
gossip  gossip-186885  lachesis  lachesis-186885

**_These files are download and untar from opera-pruned_26-Jan-2023-11-04.tar.gz which i download it several days agao_**

~# _opera --datadir /data --genesis /data/mainnet.g_
INFO [02-06|13:57:52.887] Maximum peer count                       total=50
INFO [02-06|13:57:52.888] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [02-06|13:57:52.888] Genesis file is a known preset           name="Mainnet-109331 with pruned MPT"
Fatal: Failed to make engine: failed to open existing databases: resource temporarily unavailable

~# _opera version_
Go-Opera
Version: 1.1.1-rc.2
Git Commit: 489662666ab1fd32935e33eac514844a2b3d2a72
Git Commit Date: 1656248907
Architecture: amd64
Protocol Versions: [63]
Go Version: go1.17.5
Operating System: linux
GOPATH=
GOROOT=

**it run well with an empty dir**
~# _opera --datadir /data_empty --genesis /data/mainnet.g_
INFO [02-06|13:58:56.754] Maximum peer count                       total=50
INFO [02-06|13:58:56.755] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [02-06|13:58:56.755] Genesis file is a known preset           name="Mainnet-109331 with pruned MPT"
INFO [02-06|13:58:56.788] Applying genesis state
INFO [02-06|13:58:56.789] - Reading epochs
INFO [02-06|13:59:58.737] - Reading epochs                         progress=65.66% elapsed=1m1.947s eta=38.886s
INFO [02-06|14:01:08.884] - Reading blocks
INFO [02-06|14:02:19.351] - Reading blocks                         progress=0.12%  elapsed=1m10.467s eta=18h47m32.798s

**Comment by uprendis** [comment]
Hello @past2017,
Good day to you!
It looks like there's an issue with the downloaded archive. Please note that downloading somebody's archive is very insecure, as such an archive may be easily loaded with malicious data
Instead, please just use snapsync. It'll also be faster than downloading an archive and syncing against it.
In a case you need an archive node (which you don't, according to your question), then use latest archive genesis file. Those were not updated for some time but we have to release updated archive genesis files in future.

**Comment by quan8** [comment]
@past2017  do you see the .chaindata folder after untar?

**Comment by quan8** [comment]
if you run with the datadir /data, then place chaindata folder under it.

ls /data/chaindata
gossip gossip-186885 lachesis lachesis-186885
