### ISSUE TITLE
Rebuilding events table is extremely slow

### ISSUE THREAD

**Issue by linearray** [Fantom-foundation/go-opera#433]
**Describe the bug**
After downloading and unpacking a pruned snapshot from the snapshot server resulting in a 902 GB datadir, using `--db.migration.mode rebuild --db.preset ldb-1` is extremely slow once the `events` table is reached and becomes progressively slower.

During the first minute of migration approximately 52000 files were written to disk. After 36 hours a mere 287 files were written to disk within a minute.

The opera process continuously uses one CPU core during the operation. 1.5 million ~10KB files have been written to `chaindata/leveldb-fsh/events` so far.

**To Reproduce**
1. Unpack a snapshot (which is in `legacy-ldb` format, I believe)
2. Run opera with `--db.migration.mode rebuild --db.preset ldb-1`
3. Once the migration reaches the `gossip/e` table, after a while write speeds do not exceed 70 KB/sec (measured by `du -s` at 1 minute intervals, dividing the result by `60`).

**Expected behavior**
The release notes mention speeds around 100GB/h, i.e. 27 MB/sec

**Desktop (please complete the following information):**
- opera v1.1.2-rc.5
- FreeBSD 13.1
- go 1.18.5 and 1.19.6 have been tried
- There is a lot of free space on the NVMe SSD
- Several CPU cores are unused

**Additional context**
```
INFO [02-27|14:19:28.322] Compacting DB                            name=gossip/Lt                        until=FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF04
INFO [02-27|14:21:21.526] Transforming DB layout                   db="gossip/!"
INFO [02-27|14:21:26.893] Transforming DB layout                   db=gossip/#
INFO [02-27|14:21:30.072] Transforming DB layout                   db=gossip/$
INFO [02-27|14:21:54.665] Transforming DB layout                   db=gossip/%
INFO [02-27|14:22:56.778] Transforming DB layout                   db=gossip/&
INFO [02-27|14:23:02.854] Transforming DB layout                   db=gossip/(
INFO [02-27|14:23:08.590] Transforming DB layout                   db=gossip/*
INFO [02-27|14:24:08.412] Transforming DB layout                   db=gossip/@
INFO [02-27|14:25:13.834] Transforming DB layout                   db=gossip/B
INFO [02-27|14:27:28.153] Compacting DB                            name=gossip/B                         until=end
INFO [02-27|14:27:47.613] Transforming DB layout                   db=gossip/D
INFO [02-27|14:28:09.477] Transforming DB layout                   db=gossip/M
INFO [02-27|14:59:07.354] Compacting DB                            name=gossip/M                         until=FFFF
INFO [02-27|15:00:07.354] Compacting DB                            name=gossip/M                         until=FFFF
INFO [02-27|15:00:19.040] Transforming DB layout                   db=gossip/P
INFO [02-27|15:00:33.197] Transforming DB layout                   db=gossip/U
INFO [02-27|15:00:36.251] Transforming DB layout                   db=gossip/V
INFO [02-27|15:00:42.005] Transforming DB layout                   db=gossip/X
INFO [02-27|15:01:26.150] Transforming DB layout                   db=gossip/^
INFO [02-27|15:01:33.450] Transforming DB layout                   db=gossip/_
INFO [02-27|15:01:41.855] Transforming DB layout                   db=gossip/b
INFO [02-27|15:04:32.875] Compacting DB                            name=gossip/b                         until=end
INFO [02-27|15:05:30.638] Transforming DB layout                   db=gossip/e
<< has been at it for 36 hours >>
```

invocation:
```
     bin/opera                                   \
       --genesis     /svc/fantom/var/mainnet.g   \
       --datadir     /svc/fantom/var/            \
       --cache       20000                       \
       --v5disc                                  \
       --maxpeers    150                         \
       --http                                    \
       --http.api    txpool,eth                  \
       --http.addr   0.0.0.0                     \
       --http.vhosts '*'                         \
       --ws                                      \
       --ws.api      txpool,eth                  \
       --ws.origins  '*'                         \
       --syncmode    snap                        \
       --unlock     {{redacted}}         \
       --password    /svc/fantom/var/geth.pass  \
       --allow-insecure-unlock  \
       --verbosity 3 \
       --gcmode full \
       --db.migration.mode rebuild \
       --db.preset ldb-1
```

**Comment by uprendis** [comment]
Hello @linearray ,
Good day to you!
I think the issue might be related to LevelDB compaction. In order to check it, please try to stop the node, run `bin/opera --datadir /svc/fantom/var/ --cache 20000 --db.preset ldb-1 db compact` and then resume the previously stopped rebuilding process
Please don't change the migration mode to `reformat` on this datadir, now when you've already started `rebuild` process. You may run `reformat` on a newly unpacked snapshot though

**Comment by linearray** [comment]
Thank you for the quick reply and good day to you too!

This reduced the number of tables/files to around 7000 and the speed was up to about 2MB/sec. However,

* It already dropped again to 600 KB/sec as the number of tables increased to 300k rapidly
* I do not understand where the slowdown was coming from, but that is probably because I am not very familiar with LevelDB. `opera` wasn't doing much reading either, it was just using CPU, so I don't know why the number of tables has a large effect.

**Comment by uprendis** [comment]
You can stop it for now, I'll send you an optimized version for you to try

**Comment by uprendis** [comment]
Please try `db compact` one more time, after which try running this version: https://github.com/uprendis/go-opera/tree/feature/autocompact
It'll automatically ask LevelDB to explicitly compact previously inserted data roughly once per a few minutes. It might be possible that compaction range is too large (or too small) - compaction-related performance issues differ from run to run and from hardware to hardware
You can change compaction range by `nano +49 integration/legacy_migrate.go` on line
```
		return batched.Wrap(autocompact.Wrap(m.openDst(), 32*opt.GiB))
```
, where you can adjust `32` to a different number. If a different number works better for, please let me know

This number doesn't necessarily correspond to disk space 1:1, it's data size before it written into the DB

**Comment by linearray** [comment]
Thank you so much for this! It seems to be working as write speeds are fairly good and the migration seems to make progress.

I can already say that 32 GB is far too big. The original migration essentially stalled with less than 20 GB `events` written in total.

I tried a few numbers and am currently running it with a 1 GB threshold. Migration of some tables is a bit slower, some are a bit faster, but at least for the `events` table that appears to be a good number. Compaction only takes ~5 seconds every 2 minutes or so, it doesn't appear to have a big performance impact. It is possible though that overall 2 GB is better.

**Comment by linearray** [comment]
Migrating the ~900 GB took ~21 hours. I don't plan on migrating another node anytime soon, so I'm afraid I probably will not be able to test a different number for the compaction threshold, but 1 GB worked for me.

**Comment by linearray** [comment]
Problem seems to be solved, closing. Thanks again!
