### ISSUE TITLE
RPC sub event ordering

### ISSUE THREAD

**Issue by kaber2** [Fantom-foundation/go-opera#452]
When subscribing to events, I sometimes receive events in an improper order, meaning an event b received after an event a does not have blocknum_b > blocknum_a || (blocknum_b == blocknum_a && logidx_b > logidx_a), or in simple words, blocknum/logidx are not strictly increasing. This applies to events received on a single subscription, using a single RPC connection. All other blockchains I work with deliver events properly ordered.

I can of course easily just reorder the events myself, but for processing these events, what is the proper order to have the same outcome as in the blockchain itself? Order by blocknum/logidx? Or process in the order received?

Thanks!

**Comment by quan8** [comment]
Hi @kaber2 We don't rely on a single block proposer unlike the blockchains you mentioned.
For more info, please see the following page:
https://github.com/Fantom-foundation/go-opera/wiki/EVM
Thanks.

**Comment by kaber2** [comment]
Hello @quan8, thanks for your response.

I understand that, but my question is not regarding gas price ordering, but absolute event ordering. Looking at gossip/filter/filter.go:indexedLogs(), a TxIndex is assigned based on f.backend.GetTxPosition().

Is my assumption correct that this implies that in order to process the events in the order in which the EVM processed them, I should simply sort by TxIndex (or maybe gossip/filters/ should do that sorting instead)?

**Comment by rus-alex** [comment]
Hi @kaber2 ! Yes, you should sort by blocknum/txindex/logidx.
RPC searches events by few parallel threads, each of them sends events to output immediately for performance purpose. Unfortunately, this approach does not allow to sort found events on rpc-server side.

**Comment by kaber2** [comment]
@rus-alex Thank you for the clarification.
