### ISSUE TITLE
Fatal: Failed to make engine: incompatible chainstore DB layout: DB name for 'gossip-211968' doesn't match to previous instance: 'epoch-211968' != 'gossip-211968'. Try to use 'db transform' to recover

### ISSUE THREAD

**Issue by zhwindy** [Fantom-foundation/go-opera#458]
My Opera Version: 1.1.2-rc.5
with --genesis mainnet-109331-no-history.g
and --db.migration.mode 'rebuild' --db.preset 'ldb-1'
the running error:

Fatal: Failed to make engine: incompatible chainstore DB layout: DB name for 'gossip-211968' doesn't match to previous instance: 'epoch-211968' != 'gossip-211968'. Try to use 'db transform' to recover

how to fix this ?

**Comment by quan8** [comment]
Hi @zhwindy , please check https://docs.fantom.foundation/node/run-a-read-only-node.
You can run new node without --db.migration.mode rebuild.
