### ISSUE TITLE
Info about Slashing

### ISSUE THREAD

**Issue by soltrac** [Fantom-foundation/go-opera#459]
Hello,

I would like to have more info about slashing reasons for validators.

Some validator (I'm not going to post its ID) is creating events with txs that a not modified validator would create. I have not FTMs enough in testnet to create a validator and prove this theory, but I'm pretty sure about that because I'm checking all events created by this validator.

Should this action create a slash? I understand that not, but if not, apart of double signing, what actions are slashable?

**Comment by quan8** [comment]
Slashing applies to validators with malicious activities, such as double signing and multiple instance run. For other kinds of activities, it will depend on the severity and thus appropriate penalty / slashing will be applied.

Nodes are supposed to run unmodified latest official release. Nodes running unmodified opera version do so at their own risk.

Interested people can subscribe to check out our new release and upgrade announcements (https://twitter.com/FantomFDN, https://t.me/fantomvalidators).

**Comment by mtyou** [comment]
> Slashing applies to validators with malicious activities, such as double signing and multiple instance run. For other kinds of activities, it will depend on the severity and thus appropriate penalty / slashing will be applied.
> 
> Nodes are supposed to run unmodified latest official release. Nodes running unmodified opera version do so at their own risk.
> 
> Interested people can subscribe to check out our new release and upgrade announcements (https://twitter.com/FantomFDN, https://t.me/fantomvalidators).

Is it allowed to the behavior of Validator 119, Validator 115, and Validator 120 in a Discord channel discuss ? Or will they receive any punishment? It has been three days since the last report, and I have noticed that they are still engaging in the same behavior.

**Comment by mtyou** [comment]
> Slashing applies to validators with malicious activities, such as double signing and multiple instance run. For other kinds of activities, it will depend on the severity and thus appropriate penalty / slashing will be applied.
> 
> Nodes are supposed to run unmodified latest official release. Nodes running unmodified opera version do so at their own risk.
> 
> Interested people can subscribe to check out our new release and upgrade announcements (https://twitter.com/FantomFDN, https://t.me/fantomvalidators).

@quan8 Is it allowed to the behavior of Validator 119, Validator 115, and Validator 120 in a Discord channel discuss ? Or will they receive any punishment? It has been three days since the last report, and I have noticed that they are still engaging in the same behavior.
