### ISSUE TITLE
--metrics port not opened

### ISSUE THREAD

**Issue by Aracki** [Fantom-foundation/go-opera#460]
**Describe the bug**
opera didn't open metrics port at all.

I've started `opera` with: 
```
/opera --genesis=/mainnet-genesis.json --datadir=/root/.ethereum --cache=16384 --http --http.addr=0.0.0.0 --http.port=18545 --http.api=eth,net,web3,admin,debug,personal,txpool --http.corsdomain=* --http.vhosts=* --ws --ws.addr=0.0.0.0 --ws.port=18546 --ws.api=eth,net,web3,admin,debug,personal,txpool --ws.origins=* --port=5050 --metrics=true --metrics.addr=0.0.0.0 --metrics.port=6060
```
but 6060 is not opened at all. 

Version `1.1.0-rc.4`

**Comment by quan8** [comment]
Hi @Aracki , version 1.1.0-rc.4 is old and no longer supported. Can you try with latest version 1.1.2-rc.5 or 1.1.2-rc.6?

--datadir=/root/.ethereum ?

**Comment by Aracki** [comment]
@quan8 Do you have any public registry where you store images for `opera`?
