### ISSUE TITLE
"TypeError: cannot read property 'toString' of undefined" when running debug_traceBlockByNumber

### ISSUE THREAD

**Issue by quick-pawiromitchel** [Fantom-foundation/go-opera#468]
**Describe the bug**
When running the `callTracer`, at the end of the output I see `TypeError: cannot read property 'toString' of undefined    in server-side tracer function 'result'`

**To Reproduce**
```
{
  "method": "debug_traceBlockByNumber",
  "params": [
    "0x3CA8A5F",
    {
      "tracer": "callTracer",
      "timeout": "3000s"
    }
  ],
  "id": 1,
  "jsonrpc": "2.0"
}
```

This produces the following error
```
    {
      "error": "TypeError: cannot read property 'toString' of undefined    in server-side tracer function 'result'"
    }
```

**Version**
`v1.1.2-txtracing-rc.6-9d9f51d7-1678723682`

**Additional context**
Full log
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": [
    {
      "result": {
        "type": "CALL",
        "from": "0x23abcb82f468e3422a7212d4ad47cc2dd39162a3",
        "to": "0xf491e7b69e4244ad4002bc14e878a34207e38c29",
        "value": "0x0",
        "gas": "0x30942",
        "gasUsed": "0x14de4",
        "input": "0x38ed17390000000000000000000000000000000000000000000000145c1974901224000000000000000000000000000000000000000000000000000000000000073e753300000000000000000000000000000000000000000000000000000000000000a000000000000000000000000023abcb82f468e3422a7212d4ad47cc2dd39162a300000000000000000000000000000000000000000000000000000000647d94f7000000000000000000000000000000000000000000000000000000000000000200000000000000000000000021be370d5312f44cb42ce377bc9b8a0cef1a4c83000000000000000000000000049d68029688eabf473097a2fc38ef61633a3c7a",
        "output": "0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000145c1974901224000000000000000000000000000000000000000000000000000000000000073e83ed",
        "calls": [
          {
            "type": "STATICCALL",
            "from": "0xf491e7b69e4244ad4002bc14e878a34207e38c29",
            "to": "0x5965e53aa80a0bcf1cd6dbdd72e6a9b2aa047410",
            "gas": "0x2eac1",
            "gasUsed": "0x9c8",
            "input": "0x0902f1ac",
            "output": "0x0000000000000000000000000000000000000000000000000000008556bccda20000000000000000000000000000000000000000000175eb326160a64c6cb4ef00000000000000000000000000000000000000000000000000000000647d90f0"
          },
          {
            "type": "CALL",
            "from": "0xf491e7b69e4244ad4002bc14e878a34207e38c29",
            "to": "0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83",
            "value": "0x0",
            "gas": "0x2ccbc",
            "gasUsed": "0x57be",
            "input": "0x23b872dd00000000000000000000000023abcb82f468e3422a7212d4ad47cc2dd39162a30000000000000000000000005965e53aa80a0bcf1cd6dbdd72e6a9b2aa0474100000000000000000000000000000000000000000000000145c19749012240000",
            "output": "0x0000000000000000000000000000000000000000000000000000000000000001"
          },
          {
            "type": "CALL",
            "from": "0xf491e7b69e4244ad4002bc14e878a34207e38c29",
            "to": "0x5965e53aa80a0bcf1cd6dbdd72e6a9b2aa047410",
            "value": "0x0",
            "gas": "0x26db3",
            "gasUsed": "0xba69",
            "input": "0x022c0d9f00000000000000000000000000000000000000000000000000000000073e83ed000000000000000000000000000000000000000000000000000000000000000000000000000000000000000023abcb82f468e3422a7212d4ad47cc2dd39162a300000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000",
            "output": "0x",
            "calls": [
              {
                "type": "CALL",
                "from": "0x5965e53aa80a0bcf1cd6dbdd72e6a9b2aa047410",
                "to": "0x049d68029688eabf473097a2fc38ef61633a3c7a",
                "value": "0x0",
                "gas": "0x2308f",
                "gasUsed": "0x324e",
                "input": "0xa9059cbb00000000000000000000000023abcb82f468e3422a7212d4ad47cc2dd39162a300000000000000000000000000000000000000000000000000000000073e83ed",
                "output": "0x0000000000000000000000000000000000000000000000000000000000000001"
              },
              {
                "type": "STATICCALL",
                "from": "0x5965e53aa80a0bcf1cd6dbdd72e6a9b2aa047410",
                "to": "0x049d68029688eabf473097a2fc38ef61633a3c7a",
                "gas": "0x1fc9d",
                "gasUsed": "0x256",
                "input": "0x70a082310000000000000000000000005965e53aa80a0bcf1cd6dbdd72e6a9b2aa047410",
                "output": "0x000000000000000000000000000000000000000000000000000000854f7e49b5"
              },
              {
                "type": "STATICCALL",
                "from": "0x5965e53aa80a0bcf1cd6dbdd72e6a9b2aa047410",
                "to": "0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83",
                "gas": "0x1f8bb",
                "gasUsed": "0x1e8",
                "input": "0x70a082310000000000000000000000005965e53aa80a0bcf1cd6dbdd72e6a9b2aa047410",
                "output": "0x0000000000000000000000000000000000000000000175ff8e7ad5365e90b4ef"
              }
            ]
          }
        ]
      }
    },
    {
      "result": {
        "type": "CALL",
        "from": "0x72688d521ab17a8e803f380d9756ad5c433c1bf1",
        "to": "0x348e92517dd9de1ca79b6aeb8da038aacf599af1",
        "value": "0x0",
        "gas": "0x68d13",
        "gasUsed": "0x106e0",
        "input": "0x8119c065001200010000000000000000000000000000000000000000000000000157d0b504068da6c83afcfa0e13ba15a6696662335d5b750001000000000000000f3688098e3d50642e850a5a6ff3945f4491e985aab0ee0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000049d68029688eabf473097a2fc38ef61633a3c7a0100020200000000000f387ca0f1f47cfaadbd9009483db6a042bd2b4c6e99200001000000000000000006f000000000000000058d15e1762800000000000000000002c68af0bb1400000c0c21be370d5312f44cb42ce377bc9b8a0cef1a4c830100040000000000000f36885965e53aa80a0bcf1cd6dbdd72e6a9b2aa0474100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "output": "0x",
        "calls": [
          {
            "type": "STATICCALL",
            "from": "0x348e92517dd9de1ca79b6aeb8da038aacf599af1",
            "to": "0xa0f1f47cfaadbd9009483db6a042bd2b4c6e9920",
            "gas": "0x666ce",
            "gasUsed": "0x129",
            "input": "0x8d928af8",
            "output": "0x00000000000000000000000020dd72ed959b6147912c2e529f0a0c651c33c9ce"
          },
          {
            "type": "STATICCALL",
            "from": "0x348e92517dd9de1ca79b6aeb8da038aacf599af1",
            "to": "0x20dd72ed959b6147912c2e529f0a0c651c33c9ce",
            "gas": "0x65a84",
            "gasUsed": "0x820a",
            "input": "0xf94d4668a0f1f47cfaadbd9009483db6a042bd2b4c6e99200001000000000000000006f0",
            "output": "0x000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000003ca86f2000000000000000000000000000000000000000000000000000000000000000500000000000000000000000004068da6c83afcfa0e13ba15a6696662335d5b75000000000000000000000000049d68029688eabf473097a2fc38ef61633a3c7a000000000000000000000000321162cd933e2be498cd2267a90534a804051b1100000000000000000000000074b23882a30290451a17c44f4f05243b6b58c76d0000000000000000000000008d11ec38a3eb5e956b052f67da8bdc9bef8abf3e0000000000000000000000000000000000000000000000000000000000000005000000000000000000000000000000000000000000000000000000110c73dae60000000000000000000000000000000000000000000000000000002225ee80e700000000000000000000000000000000000000000000000000000000082669ed0000000000000000000000000000000000000000000000010f23b394c1d5a3ef000000000000000000000000000000000000000000000f88628c065a1cd2d797"
          },
          {
            "type": "CALL",
            "from": "0x348e92517dd9de1ca79b6aeb8da038aacf599af1",
            "to": "0x5965e53aa80a0bcf1cd6dbdd72e6a9b2aa047410",
            "value": "0x0",
            "gas": "0x5bf9a",
            "gasUsed": "0x9c8",
            "input": "0x0902f1ac",
            "output": "0x000000000000000000000000000000000000000000000000000000854f7e49b50000000000000000000000000000000000000000000175ff8e7ad5365e90b4ef00000000000000000000000000000000000000000000000000000000647d910f"
          },
          {
            "type": "CALL",
            "from": "0x348e92517dd9de1ca79b6aeb8da038aacf599af1",
            "to": "0x098e3d50642e850a5a6ff3945f4491e985aab0ee",
            "value": "0x0",
            "gas": "0x5aa81",
            "gasUsed": "0x3a0f",
            "input": "0x0902f1ac",
            "output": "0x000000000000000000000000000000000000000000000000000000009199d63e000000000000000000000000000000000000000000000197c061c40c08797efa00000000000000000000000000000000000000000000000000000000647d909e",
            "calls": [
              {
                "type": "DELEGATECALL",
                "from": "0x098e3d50642e850a5a6ff3945f4491e985aab0ee",
                "to": "0x01385d15c5d186daa9a53d268fbca59b3f22f28f",
                "gas": "0x58139",
                "gasUsed": "0x26f6",
                "input": "0x0902f1ac",
                "output": "0x000000000000000000000000000000000000000000000000000000009199d63e000000000000000000000000000000000000000000000197c061c40c08797efa00000000000000000000000000000000000000000000000000000000647d909e",
                "calls": [
                  {
                    "type": "STATICCALL",
                    "from": "0x098e3d50642e850a5a6ff3945f4491e985aab0ee",
                    "to": "0xbad7d3df8e1614d985c3d9ba9f6ecd32ae7dc20a",
                    "gas": "0x55fe6",
                    "gasUsed": "0x19dc",
                    "input": "0x0902f1ac",
                    "output": "0x000000000000000000000000000000000000000000000000000000009199d63e000000000000000000000000000000000000000000000197c061c40c08797efa00000000000000000000000000000000000000000000000000000000647d909e"
                  }
                ]
              }
            ]
          }
        ]
      }
    },
    {
      "result": {
        "type": "CALL",
        "from": "0x43b01b70ca06e5a0b3151f951948e150fd9eca21",
        "to": "0x72dc7fa5eeb901a34173c874a7333c8d1b34bca9",
        "value": "0x4d66daa314a7c21a",
        "gas": "0x12e5c9",
        "gasUsed": "0x2018b",
        "input": "0xc45dec2700000000000000000000000000000000000000000000000009e86515a42929fb00000000000000000000000043b01b70ca06e5a0b3151f951948e150fd9eca21000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee00000000000000000000000004068da6c83afcfa0e13ba15a6696662335d5b750000000000000000000000000000000000000000000000003782dace9d9000000000000000000000000000000000000000000000000000000000000000163343000000000000000000000000000000000000000000000000000000000000006a000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000b97ef9ef8734c71904d8002f8b6bc66dd9c48a6e0000000000000000000000000000000000000000000000000161a73201d807fa0000000000000000000000000000000000000000000000000000000000000000",
        "output": "0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000105061757361626c653a2070617573656400000000000000000000000000000000",
        "error": "execution reverted",
        "calls": [
          {
            "type": "CALL",
            "from": "0x72dc7fa5eeb901a34173c874a7333c8d1b34bca9",
            "to": "0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83",
            "value": "0x3782dace9d900000",
            "gas": "0x12545a",
            "gasUsed": "0x7be1",
            "input": "0xd0e30db0",
            "output": "0x0000000000000000000000000000000000000000000000000000000000000000"
          },
          {
            "type": "CALL",
            "from": "0x72dc7fa5eeb901a34173c874a7333c8d1b34bca9",
            "to": "0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83",
            "value": "0x0",
            "gas": "0x11c5d4",
            "gasUsed": "0x6087",
            "input": "0x095ea7b3000000000000000000000000382a9b0bc5d29e96c3a0b81ce9c64d6c8f150efb0000000000000000000000000000000000000000000000003782dace9d900000",
            "output": "0x0000000000000000000000000000000000000000000000000000000000000001"
          },
          {
            "type": "CALL",
            "from": "0x72dc7fa5eeb901a34173c874a7333c8d1b34bca9",
            "to": "0x382a9b0bc5d29e96c3a0b81ce9c64d6c8f150efb",
            "value": "0x0",
            "gas": "0x115a31",
            "gasUsed": "0xbc43",
            "input": "0x7dc2038200000000000000000000000021be370d5312f44cb42ce377bc9b8a0cef1a4c8300000000000000000000000004068da6c83afcfa0e13ba15a6696662335d5b750000000000000000000000000000000000000000000000003782dace9d900000000000000000000000000000000000000000000000000000000000000016334300000000000000000000000072dc7fa5eeb901a34173c874a7333c8d1b34bca900000000000000000000000043b01b70ca06e5a0b3151f951948e150fd9eca21",
            "error": "execution reverted",
            "calls": [
              {
                "type": "CALL",
                "from": "0x382a9b0bc5d29e96c3a0b81ce9c64d6c8f150efb",
                "to": "0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83",
                "value": "0x0",
                "gas": "0x10f320",
                "gasUsed": "0x6d3a",
                "input": "0x23b872dd00000000000000000000000072dc7fa5eeb901a34173c874a7333c8d1b34bca9000000000000000000000000286ab107c5e9083dbed35a2b5fb0242538f4f9bf0000000000000000000000000000000000000000000000003782dace9d900000",
                "output": "0x0000000000000000000000000000000000000000000000000000000000000001"
              },
              {
                "type": "CALL",
                "from": "0x382a9b0bc5d29e96c3a0b81ce9c64d6c8f150efb",
                "to": "0x286ab107c5e9083dbed35a2b5fb0242538f4f9bf",
                "value": "0x0",
                "gas": "0x107ae5",
                "gasUsed": "0x1fbc",
                "input": "0x7dc2038200000000000000000000000021be370d5312f44cb42ce377bc9b8a0cef1a4c8300000000000000000000000004068da6c83afcfa0e13ba15a6696662335d5b750000000000000000000000000000000000000000000000003782dace9d900000000000000000000000000000000000000000000000000000000000000016334300000000000000000000000072dc7fa5eeb901a34173c874a7333c8d1b34bca900000000000000000000000043b01b70ca06e5a0b3151f951948e150fd9eca21",
                "error": "execution reverted"
              }
            ]
          }
        ]
      }
    },
    {
      "error": "TypeError: cannot read property 'toString' of undefined    in server-side tracer function 'result'"
    }
  ]
}
```

**Comment by aalan3** [comment]
Here are some more blocks that have the same issue, these are close to the tip but there are once further back as well.
```
64094811
63456274
63487919
63510566
63535828
63544557
63548280
63556325
63569186
63583603
63588445
63593045
63605343
63730104
63774981
63939348
63936216
63940043
```

**Comment by hawkaa** [comment]
@HonzaDajc what are the odds that this issue will be a part of the next RC? The `geth` tracer, `debug_traceBlockByNumber` by far gives the most accurate results compared to `debug_trace` but has the aforementioned issue.

**Comment by jenikd** [comment]
This PR https://github.com/Fantom-foundation/go-opera/pull/501 solves this issue and should go into next RC

**Comment by Emadalshamery** [comment]
Please can you help me please 🙏

**Comment by Rsed19901** [comment]
> **Describe the bug**
> When running the `callTracer`, at the end of the output I see `TypeError: cannot read property 'toString' of undefined    in server-side tracer function 'result'`
> 
> **To Reproduce**
> ```
> {
>   "method": "debug_traceBlockByNumber",
>   "params": [
>     "0x3CA8A5F",
>     {
>       "tracer": "callTracer",
>       "timeout": "3000s"
>     }
>   ],
>   "id": 1,
>   "jsonrpc": "2.0"
> }
> ```
> 
> This produces the following error
> ```
>     {
>       "error": "TypeError: cannot read property 'toString' of undefined    in server-side tracer function 'result'"
>     }
> ```
> 
> **Version**
> `v1.1.2-txtracing-rc.6-9d9f51d7-1678723682`
> 
> **Additional context**
> Full log
> ```
> {
>   "jsonrpc": "2.0",
>   "id": 1,
>   "result": [
>     {
>       "result": {
>         "type": "CALL",
>         "from": "0x23abcb82f468e3422a7212d4ad47cc2dd39162a3",
>         "to": "0xf491e7b69e4244ad4002bc14e878a34207e38c29",
>         "value": "0x0",
>         "gas": "0x30942",
>         "gasUsed": "0x14de4",
>         "input": "0x38ed17390000000000000000000000000000000000000000000000145c1974901224000000000000000000000000000000000000000000000000000000000000073e753300000000000000000000000000000000000000000000000000000000000000a000000000000000000000000023abcb82f468e3422a7212d4ad47cc2dd39162a300000000000000000000000000000000000000000000000000000000647d94f7000000000000000000000000000000000000000000000000000000000000000200000000000000000000000021be370d5312f44cb42ce377bc9b8a0cef1a4c83000000000000000000000000049d68029688eabf473097a2fc38ef61633a3c7a",
>         "output": "0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000145c1974901224000000000000000000000000000000000000000000000000000000000000073e83ed",
>         "calls": [
>           {
>             "type": "STATICCALL",
>             "from": "0xf491e7b69e4244ad4002bc14e878a34207e38c29",
>             "to": "0x5965e53aa80a0bcf1cd6dbdd72e6a9b2aa047410",
>             "gas": "0x2eac1",
>             "gasUsed": "0x9c8",
>             "input": "0x0902f1ac",
>             "output": "0x0000000000000000000000000000000000000000000000000000008556bccda20000000000000000000000000000000000000000000175eb326160a64c6cb4ef00000000000000000000000000000000000000000000000000000000647d90f0"
>           },
>           {
>             "type": "CALL",
>             "from": "0xf491e7b69e4244ad4002bc14e878a34207e38c29",
>             "to": "0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83",
>             "value": "0x0",
>             "gas": "0x2ccbc",
>             "gasUsed": "0x57be",
>             "input": "0x23b872dd00000000000000000000000023abcb82f468e3422a7212d4ad47cc2dd39162a30000000000000000000000005965e53aa80a0bcf1cd6dbdd72e6a9b2aa0474100000000000000000000000000000000000000000000000145c19749012240000",
>             "output": "0x0000000000000000000000000000000000000000000000000000000000000001"
>           },
>           {
>             "type": "CALL",
>             "from": "0xf491e7b69e4244ad4002bc14e878a34207e38c29",
>             "to": "0x5965e53aa80a0bcf1cd6dbdd72e6a9b2aa047410",
>             "value": "0x0",
>             "gas": "0x26db3",
>             "gasUsed": "0xba69",
>             "input": "0x022c0d9f00000000000000000000000000000000000000000000000000000000073e83ed000000000000000000000000000000000000000000000000000000000000000000000000000000000000000023abcb82f468e3422a7212d4ad47cc2dd39162a300000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000",
>             "output": "0x",
>             "calls": [
>               {
>                 "type": "CALL",
>                 "from": "0x5965e53aa80a0bcf1cd6dbdd72e6a9b2aa047410",
>                 "to": "0x049d68029688eabf473097a2fc38ef61633a3c7a",
>                 "value": "0x0",
>                 "gas": "0x2308f",
>                 "gasUsed": "0x324e",
>                 "input": "0xa9059cbb00000000000000000000000023abcb82f468e3422a7212d4ad47cc2dd39162a300000000000000000000000000000000000000000000000000000000073e83ed",
>                 "output": "0x0000000000000000000000000000000000000000000000000000000000000001"
>               },
>               {
>                 "type": "STATICCALL",
>                 "from": "0x5965e53aa80a0bcf1cd6dbdd72e6a9b2aa047410",
>                 "to": "0x049d68029688eabf473097a2fc38ef61633a3c7a",
>                 "gas": "0x1fc9d",
>                 "gasUsed": "0x256",
>                 "input": "0x70a082310000000000000000000000005965e53aa80a0bcf1cd6dbdd72e6a9b2aa047410",
>                 "output": "0x000000000000000000000000000000000000000000000000000000854f7e49b5"
>               },
>               {
>                 "type": "STATICCALL",
>                 "from": "0x5965e53aa80a0bcf1cd6dbdd72e6a9b2aa047410",
>                 "to": "0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83",
>                 "gas": "0x1f8bb",
>                 "gasUsed": "0x1e8",
>                 "input": "0x70a082310000000000000000000000005965e53aa80a0bcf1cd6dbdd72e6a9b2aa047410",
>                 "output": "0x0000000000000000000000000000000000000000000175ff8e7ad5365e90b4ef"
>               }
>             ]
>           }
>         ]
>       }
>     },
>     {
>       "result": {
>         "type": "CALL",
>         "from": "0x72688d521ab17a8e803f380d9756ad5c433c1bf1",
>         "to": "0x348e92517dd9de1ca79b6aeb8da038aacf599af1",
>         "value": "0x0",
>         "gas": "0x68d13",
>         "gasUsed": "0x106e0",
>         "input": "0x8119c065001200010000000000000000000000000000000000000000000000000157d0b504068da6c83afcfa0e13ba15a6696662335d5b750001000000000000000f3688098e3d50642e850a5a6ff3945f4491e985aab0ee0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000049d68029688eabf473097a2fc38ef61633a3c7a0100020200000000000f387ca0f1f47cfaadbd9009483db6a042bd2b4c6e99200001000000000000000006f000000000000000058d15e1762800000000000000000002c68af0bb1400000c0c21be370d5312f44cb42ce377bc9b8a0cef1a4c830100040000000000000f36885965e53aa80a0bcf1cd6dbdd72e6a9b2aa0474100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
>         "output": "0x",
>         "calls": [
>           {
>             "type": "STATICCALL",
>             "from": "0x348e92517dd9de1ca79b6aeb8da038aacf599af1",
>             "to": "0xa0f1f47cfaadbd9009483db6a042bd2b4c6e9920",
>             "gas": "0x666ce",
>             "gasUsed": "0x129",
>             "input": "0x8d928af8",
>             "output": "0x00000000000000000000000020dd72ed959b6147912c2e529f0a0c651c33c9ce"
>           },
>           {
>             "type": "STATICCALL",
>             "from": "0x348e92517dd9de1ca79b6aeb8da038aacf599af1",
>             "to": "0x20dd72ed959b6147912c2e529f0a0c651c33c9ce",
>             "gas": "0x65a84",
>             "gasUsed": "0x820a",
>             "input": "0xf94d4668a0f1f47cfaadbd9009483db6a042bd2b4c6e99200001000000000000000006f0",
>             "output": "0x000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000003ca86f2000000000000000000000000000000000000000000000000000000000000000500000000000000000000000004068da6c83afcfa0e13ba15a6696662335d5b75000000000000000000000000049d68029688eabf473097a2fc38ef61633a3c7a000000000000000000000000321162cd933e2be498cd2267a90534a804051b1100000000000000000000000074b23882a30290451a17c44f4f05243b6b58c76d0000000000000000000000008d11ec38a3eb5e956b052f67da8bdc9bef8abf3e0000000000000000000000000000000000000000000000000000000000000005000000000000000000000000000000000000000000000000000000110c73dae60000000000000000000000000000000000000000000000000000002225ee80e700000000000000000000000000000000000000000000000000000000082669ed0000000000000000000000000000000000000000000000010f23b394c1d5a3ef000000000000000000000000000000000000000000000f88628c065a1cd2d797"
>           },
>           {
>             "type": "CALL",
>             "from": "0x348e92517dd9de1ca79b6aeb8da038aacf599af1",
>             "to": "0x5965e53aa80a0bcf1cd6dbdd72e6a9b2aa047410",
>             "value": "0x0",
>             "gas": "0x5bf9a",
>             "gasUsed": "0x9c8",
>             "input": "0x0902f1ac",
>             "output": "0x000000000000000000000000000000000000000000000000000000854f7e49b50000000000000000000000000000000000000000000175ff8e7ad5365e90b4ef00000000000000000000000000000000000000000000000000000000647d910f"
>           },
>           {
>             "type": "CALL",
>             "from": "0x348e92517dd9de1ca79b6aeb8da038aacf599af1",
>             "to": "0x098e3d50642e850a5a6ff3945f4491e985aab0ee",
>             "value": "0x0",
>             "gas": "0x5aa81",
>             "gasUsed": "0x3a0f",
>             "input": "0x0902f1ac",
>             "output": "0x000000000000000000000000000000000000000000000000000000009199d63e000000000000000000000000000000000000000000000197c061c40c08797efa00000000000000000000000000000000000000000000000000000000647d909e",
>             "calls": [
>               {
>                 "type": "DELEGATECALL",
>                 "from": "0x098e3d50642e850a5a6ff3945f4491e985aab0ee",
>                 "to": "0x01385d15c5d186daa9a53d268fbca59b3f22f28f",
>                 "gas": "0x58139",
>                 "gasUsed": "0x26f6",
>                 "input": "0x0902f1ac",
>                 "output": "0x000000000000000000000000000000000000000000000000000000009199d63e000000000000000000000000000000000000000000000197c061c40c08797efa00000000000000000000000000000000000000000000000000000000647d909e",
>                 "calls": [
>                   {
>                     "type": "STATICCALL",
>                     "from": "0x098e3d50642e850a5a6ff3945f4491e985aab0ee",
>                     "to": "0xbad7d3df8e1614d985c3d9ba9f6ecd32ae7dc20a",
>                     "gas": "0x55fe6",
>                     "gasUsed": "0x19dc",
>                     "input": "0x0902f1ac",
>                     "output": "0x000000000000000000000000000000000000000000000000000000009199d63e000000000000000000000000000000000000000000000197c061c40c08797efa00000000000000000000000000000000000000000000000000000000647d909e"
>                   }
>                 ]
>               }
>             ]
>           }
>         ]
>       }
>     },
>     {
>       "result": {
>         "type": "CALL",
>         "from": "0x43b01b70ca06e5a0b3151f951948e150fd9eca21",
>         "to": "0x72dc7fa5eeb901a34173c874a7333c8d1b34bca9",
>         "value": "0x4d66daa314a7c21a",
>         "gas": "0x12e5c9",
>         "gasUsed": "0x2018b",
>         "input": "0xc45dec2700000000000000000000000000000000000000000000000009e86515a42929fb00000000000000000000000043b01b70ca06e5a0b3151f951948e150fd9eca21000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee00000000000000000000000004068da6c83afcfa0e13ba15a6696662335d5b750000000000000000000000000000000000000000000000003782dace9d9000000000000000000000000000000000000000000000000000000000000000163343000000000000000000000000000000000000000000000000000000000000006a000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee000000000000000000000000b97ef9ef8734c71904d8002f8b6bc66dd9c48a6e0000000000000000000000000000000000000000000000000161a73201d807fa0000000000000000000000000000000000000000000000000000000000000000",
>         "output": "0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000105061757361626c653a2070617573656400000000000000000000000000000000",
>         "error": "execution reverted",
>         "calls": [
>           {
>             "type": "CALL",
>             "from": "0x72dc7fa5eeb901a34173c874a7333c8d1b34bca9",
>             "to": "0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83",
>             "value": "0x3782dace9d900000",
>             "gas": "0x12545a",
>             "gasUsed": "0x7be1",
>             "input": "0xd0e30db0",
>             "output": "0x0000000000000000000000000000000000000000000000000000000000000000"
>           },
>           {
>             "type": "CALL",
>             "from": "0x72dc7fa5eeb901a34173c874a7333c8d1b34bca9",
>             "to": "0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83",
>             "value": "0x0",
>             "gas": "0x11c5d4",
>             "gasUsed": "0x6087",
>             "input": "0x095ea7b3000000000000000000000000382a9b0bc5d29e96c3a0b81ce9c64d6c8f150efb0000000000000000000000000000000000000000000000003782dace9d900000",
>             "output": "0x0000000000000000000000000000000000000000000000000000000000000001"
>           },
>           {
>             "type": "CALL",
>             "from": "0x72dc7fa5eeb901a34173c874a7333c8d1b34bca9",
>             "to": "0x382a9b0bc5d29e96c3a0b81ce9c64d6c8f150efb",
>             "value": "0x0",
>             "gas": "0x115a31",
>             "gasUsed": "0xbc43",
>             "input": "0x7dc2038200000000000000000000000021be370d5312f44cb42ce377bc9b8a0cef1a4c8300000000000000000000000004068da6c83afcfa0e13ba15a6696662335d5b750000000000000000000000000000000000000000000000003782dace9d900000000000000000000000000000000000000000000000000000000000000016334300000000000000000000000072dc7fa5eeb901a34173c874a7333c8d1b34bca900000000000000000000000043b01b70ca06e5a0b3151f951948e150fd9eca21",
>             "error": "execution reverted",
>             "calls": [
>               {
>                 "type": "CALL",
>                 "from": "0x382a9b0bc5d29e96c3a0b81ce9c64d6c8f150efb",
>                 "to": "0x21be370d5312f44cb42ce377bc9b8a0cef1a4c83",
>                 "value": "0x0",
>                 "gas": "0x10f320",
>                 "gasUsed": "0x6d3a",
>                 "input": "0x23b872dd00000000000000000000000072dc7fa5eeb901a34173c874a7333c8d1b34bca9000000000000000000000000286ab107c5e9083dbed35a2b5fb0242538f4f9bf0000000000000000000000000000000000000000000000003782dace9d900000",
>                 "output": "0x0000000000000000000000000000000000000000000000000000000000000001"
>               },
>               {
>                 "type": "CALL",
>                 "from": "0x382a9b0bc5d29e96c3a0b81ce9c64d6c8f150efb",
>                 "to": "0x286ab107c5e9083dbed35a2b5fb0242538f4f9bf",
>                 "value": "0x0",
>                 "gas": "0x107ae5",
>                 "gasUsed": "0x1fbc",
>                 "input": "0x7dc2038200000000000000000000000021be370d5312f44cb42ce377bc9b8a0cef1a4c8300000000000000000000000004068da6c83afcfa0e13ba15a6696662335d5b750000000000000000000000000000000000000000000000003782dace9d900000000000000000000000000000000000000000000000000000000000000016334300000000000000000000000072dc7fa5eeb901a34173c874a7333c8d1b34bca900000000000000000000000043b01b70ca06e5a0b3151f951948e150fd9eca21",
>                 "error": "execution reverted"
>               }
>             ]
>           }
>         ]
>       }
>     },
>     {
>       "error": "TypeError: cannot read property 'toString' of undefined    in server-side tracer function 'result'"
>     }
>   ]
> }
> ```
>

**Comment by Rsed19901** [comment]
Kob😍😍

**Comment by Bahman1983EMH** [comment]
> 

> 

- > **__**
