### ISSUE TITLE
Pebble success on 14 servers

### ISSUE THREAD

**Issue by kaber2** [Fantom-foundation/go-opera#470]
Hello,

just thought you might appreciate the feedback since Pebble is still considered Beta. I've successfully converted 14 servers, in all cases the conversion ran fine, and the node has been running without problems since.

As I do have periods of high RPC load, this seems to have help reduce the I/O-Load. I haven't done any comparative measurements, but I noticed periods of very high sustained I/O with Fantom before, now it looks way more reasonable.

Nice job!

**Comment by vanpt1114** [comment]
Hey @kaber2 , may I wonder how long it takes to finish syncing a RPC node of PebbleDB? My current VM is still on "State heal in progress" for nearly 2 weeks.

**Comment by kaber2** [comment]
I did a database conversion from ldb, that went pretty fast, IIRC maybe 6 hours.

**Comment by vanpt1114** [comment]
@kaber2 May i have the command the convert it from goleveldb to pebble db? That document seems not enough.

**Comment by kaber2** [comment]
> @kaber2 May i have the command the convert it from goleveldb to pebble db? That document seems not enough.

I unfortunately don't have the commands I used available anymore, but I do recall just following the documentation, nothing else.
