### ISSUE TITLE
opera attach failing with connection refused

### ISSUE THREAD

**Issue by fvasquez** [Fantom-foundation/go-opera#485]
**Describe the bug**
$ opera attach
Fatal: Unable to attach to remote opera: dial unix /home/ubuntu/.opera/opera.ipc: connect: connection refused

**To Reproduce**
1. Open a terminal
    ssh into AWS Ubuntu 22.04 LTS EC2 instance as ubuntu user
3. Start opera node
    $ nohup /usr/local/bin/opera ... 2>> opera.log &
4. Wait for opera node to sync with blockchain
5. Open another terminal
     ssh into same AWS Ubuntu 22.04 LTS EC2 instance as ubuntu user
6. $ opera account new
7. Fund wallet
8. $ opera validator new
9. $ opera attach

**Expected behavior**
Expected to connect to opera node started in original terminal.
Expected to see a JavaScript console prompt.

**Server (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS

**Additional context**
I Git cloned and built go-opera in /home/ubuntu/ as the default ubuntu user. I moved the opera executable to /usr/local/bin/ after that.

**Comment by quan8** [comment]
For setting up a node, please check this guide: https://docs.fantom.foundation/node/run-a-read-only-node.
If --datadir flag is enabled, you should specify it when attaching.
Please contact our support on Discord if need further help.
