### ISSUE TITLE
After upgrading to 1.1.3-RC.5, an error occurred when restarting synchronization.

### ISSUE THREAD

**Issue by coinbase-op** [Fantom-foundation/go-opera#522]
os:
ubuntu:20.04

**To Reproduce**
opera --identity xtftm --datadir /ftm --http --http.addr 0.0.0.0 --http.api=eth,web3,net,ftm,admin --cache 8192 --allow-insecure-unlock --http.vhosts=*

root@5328822386：/ftm# ls 
chaindata  go-opera  keystore  mainnet-109331-pruned-mpt.g  mainnet-171200-pruned-mpt.g

**Screenshots**
INFO [10-27|03:21:26.187] Maximum peer count                       total=50
INFO [10-27|03:21:26.187] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [10-27|03:21:54.254] Genesis is already written               name=main id=250 genesis=0x4a53c5445584b3bfc20dbfb2ec18ae20037c716f3ba2d9e1da768a9deca17cb4
INFO [10-27|03:21:54.258] Loaded local transaction journal         transactions=0 dropped=0
INFO [10-27|03:21:54.258] Regenerated local transaction journal    transactions=0 accounts=0
INFO [10-27|03:21:54.259] Starting peer-to-peer node               instance=go-opera/xtftm/v1.1.3-rc.5/linux-amd64/go1.17.2
INFO [10-27|03:21:54.315] New local node record                    seq=3337 id=1bf01ac8a840de67 ip=127.0.0.1 udp=5050 tcp=5050
INFO [10-27|03:21:54.327] Started P2P networking                   self=enode://de37c792ca9cec4e87dd36d2a5448c0091810632086ca1b0f40037e856aa8c9498732880e444e237a4c01583f64d6e0182f92cfdce23073edfaeac285ec8a835@127.0.0.1:5050
INFO [10-27|03:21:54.328] IPC endpoint opened                      url=/ftm/opera.ipc
INFO [10-27|03:21:54.328] HTTP server started                      endpoint=[::]:18545 prefix= cors= vhosts=*
INFO [10-27|03:21:54.330] HTTP server stopped                      endpoint=[::]:18545
INFO [10-27|03:21:54.330] IPC endpoint closed                      url=/ftm/opera.ipc
Fatal: Error starting protocol stack: cannot halt snapsync and start fullsync
Fatal: Error starting protocol stack: cannot halt snapsync and start fullsync

**Comment by quan8** [comment]
Hi @coinbase-op , it's not reproducible. You may stop the node properly and start it again.
Btw, it's not recommended to enable admin namespace and insecure unlock over http.
