### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by kaber2** [Fantom-foundation/go-opera#528]
I'm constantly being confused by your versioning scheme, whether a version is intended to be used or not, as every version is called "rc", which is usually understood to mean "release candidate", so *not* a release.

I'm not sure if you assign a different meaning to "rc", but maybe you could consider using a more clear versioning scheme or explicitly stating whether a version is to be used.

**Comment by quan8** [comment]
Hi @kaber2 , Our releases are available at https://github.com/Fantom-foundation/go-opera/releases.
Please follow our Discord, Telegram and Twitter for latest announcements.

**Comment by kaber2** [comment]
My point was not that I don't get information about the releases, just that your use of "RC" differs from how everyone else in the world is using it and that it might be less confusing to use it in the commonly understood way.
