### ISSUE TITLE
Here are some more blocks that have the same issue, these are close to the tip but there are once further back as well.

### ISSUE THREAD

**Issue by MichealSD13** [Fantom-foundation/go-opera#531]
Here are some more blocks that have the same issue, these are close to the tip but there are once further back as well.
```
64094811
63456274
63487919
63510566
63535828
63544557
63548280
63556325
63569186
63583603
63588445
63593045
63605343
63730104
63774981
63939348
63936216
63940043
```

_Originally posted by @aalan3 in https://github.com/Fantom-foundation/go-opera/issues/468#issuecomment-1593299626_

**Comment by Emadalshamery** [comment]
84QXahN82288Z7VSwnv3qzkamcqi54nbCQuemxhR3MX8

Please can you help me
