### ISSUE TITLE
Slow node sync with non-pruned snapshot

### ISSUE THREAD

**Issue by nebojsa-ristovic** [Fantom-foundation/go-opera#534]
Hi,

I started archive node from [non-pruned snapshot](https://snapshot.fantom.network/files/nonpruned/) but sync speed is lower than network block rate - looks like my node will never reach the sync. 
Flags I use are: 
--db.preset ldb-1 (as your documentation suggested)
--db.migration.mode reformat (since I wasn't able to start node without this flag) 

My questions are:
1. Will you update newer snapshot since current one is almost 2 months old?
2. Are there any ways to speed up node sync except from cache increase (currently use 16Gb of cache)?

**Comment by quan8** [comment]
Hi @nebojsa-ristovic ,
That snapshot was built from a node running with --db.preset ldb-1. You don't need to specify --db.migration.mode reformat.

For trouble shooting syncing issue, this guide may help: https://docs.fantom.foundation/node/troubleshooting#id-4.2-slow-syncing

**Comment by nebojsa-ristovic** [comment]
Hi @quan8, node wasn't able to start without --db.migration.mode flag. 
But anyway, we are almost done syncing, so my questions are stale. 

Thanks for your answer anyway.
