### ISSUE TITLE
Snap sync from scratch never finishes sync

### ISSUE THREAD

**Issue by hdiass** [Fantom-foundation/go-opera#536]
**Describe the bug**
Been syncing a node from scratch with snapsync, and the `--db.preset=ldb-1`  but the sync never finishes, last year around the june i was able to sync this node from scratch using same configs.

**To Reproduce**
Try to snapsync a fullnode from scratch.

**Expected behavior**
Expected to see a snap sync finishes in less than 48h.

**Additional context**
`v1.1.3-rc.5`

**Comment by valamidev** [comment]
Same here, it did stuck in infinite State heal:
After ~1 Week:
`02-01|13:01:50.294] State heal in progress                   accounts=741,112@48.77MiB     slots=2,065,457@141.94MiB   codes=77@837.83KiB       nodes=18,007,317@6.09GiB   pending=22874`

It was a on a Machine with basically infinite resources, `m7i.24xlarge.

**Comment by quan8** [comment]
Hi @hdiass , @valamidev , 
which command did you use to run your node?
You may try with the following command:
nohup ./opera --genesis mainnet-109331-no-history.g --datadir /path/snapsync/.opera --maxpeers 135 --cache 15000 --db.preset ldb-1 --syncmode snap &

**Comment by hdiass** [comment]
Hello @quan8 , i use basically your command, just added the maxpeers and cache args. Node is running for 2 hours+ with those and still in that state healing phase..Will leave it for the weekend to see if it catches up..but not very faithful

**Comment by hdiass** [comment]
So far haven't synced

**Comment by hdiass** [comment]
Checked today, and still the same

**Comment by hdiass** [comment]
Can you advise on what should i do to make snapsync work ?

**Comment by hdiass** [comment]
10 days and still same

**Comment by valamidev** [comment]
Same here, it will never finish the state heal process.

**Comment by hdiass** [comment]
Impressive, last june i was able to sync this in 1 day with snapsync..

**Comment by quan8** [comment]
Hi @valamidev @hdiass , you may check this guide:
 https://docs.fantom.foundation/node/troubleshooting#id-4.2-slow-syncing
 
There are few people who got their node set up this week within a day after replacing their disk. So possibly you'll need to tweak your machine. For further support, please go to our discord channel.

**Comment by hdiass** [comment]
ended up being the flag `--gcmode=light` the problem, removed it synced in 1 day
