### ISSUE TITLE
Epoch state reading failed: genesis not applied

### ISSUE THREAD

**Issue by valamidev** [Fantom-foundation/go-opera#537]
Hi, 

we still try to setup an Opera node, this time from Genesis, so we followed the steps to restore from a snapshot: https://docs.fantom.foundation/node/tutorials/snapshot-download.

Downloading, unzipping and moving the chaindata the desired folder, then first launch ~20-30 minutes it is processing without any output, then it throw the following error message and stay a in a forever restart loop.

`Epoch state reading failed: genesis not applied`
restart
`Epoch state reading failed: genesis not applied`
...

The following args are used for the Node:

```
opera \
  --nousb \
  --verbosity 3 \
  --cache 30000 \
  --db.preset "ldb-1" \
  --syncmode full \
  --gcmode full \
  --http \
  --http.api "eth,ftm,net,web3" \
  --http.addr "0.0.0.0" \
  --http.vhosts "*" \
  --http.corsdomain "*" \
  --http.port "18545" \
  --ws \
  --ws.origins "*" \
  --ws.addr "0.0.0.0" \
  --ws.api "eth,ftm,net,web3" \
  --ws.port "18546" 
````
 
We are using the pruned Snapshot:

`https://snapshot.fantom.network/files/pruned/`

**Comment by quan8** [comment]
Hi @valamidev , make sure download and unzipping are not interrupted. You may remove the old /oldpath/.opera/chaindata first before moving the new uncompressed data into it.
then run:
nohup opera  --nousb  --cache 30000 --cache 140 &

For further support, please go to our discord.
