### ISSUE TITLE
Genesis file got removed, download path rendered invalid

### ISSUE THREAD

**Issue by SimonKraus** [Fantom-foundation/go-opera#558]
**Describe the bug**
The readme.md is referencing [Lachesis Launch Repo](https://github.com/Fantom-foundation/lachesis_launch) for the node setup and in there the [setup shell scripts](https://github.com/Fantom-foundation/lachesis_launch/blob/master/docs/setup-readonly-node.sh) use the following download path for the genesis file:
https://download.fantom.network/mainnet-171200-pruned-mpt.g

This file does no longer exist and the requests return an 404 error code.

**To Reproduce**
self-explanatory

**Expected behavior**
file needs to be there

**Screenshots**
![fantom-genesis-404](https://github.com/user-attachments/assets/4ce2f309-56f5-494a-9f6f-1722debb0506)

**Comment by jmpike** [comment]
Added permanent redirect to support the new location of the Opera genesis downloadable.
