### ISSUE TITLE
The number of concurrent transactions is too low. How to increase the number of packaged transactions?

### ISSUE THREAD

**Issue by Ten-Ou** [Fantom-foundation/go-opera#93]
I execute contract transactions and squeeze them into the transaction pool, and each package will only process a very small number (10) transactions.

**Comment by uprendis** [comment]
Hello @Ten-Ou ,
Good day to you!
The validators limit number of originated transactions from a single account. That's one of the measures to protect validators from originating conflicting transactions, as the consensus is asynchronous and, at a time of an event emission, validators don't know in what exact order the transactions will be executed

You would have to send transactions from multiple accounts you want more than ~10 transactions per block

**Comment by uprendis** [comment]
Here's a little bit more details on how it works: https://github.com/Fantom-foundation/go-opera/wiki/Tx-Origination

**Comment by linyintao2010** [comment]
> Here's a little bit more details on how it works: https://github.com/Fantom-foundation/go-opera/wiki/Tx-Origination

Hello @uprendis ，I have a question，Maybe I have a wrong understanding of high throughput，What exactly does high throughput mean here?
Fantom is a fast, high-throughput open-source smart contract 。Doesn't high throughput mean tps, or is it possible to achieve high throughput as an account address？
thanks

**Comment by quan8** [comment]
@Ten-Ou @linyintao2010  Thanks for your interests. We focus on both TTF and TPS and try to balance between them.
