### ISSUE TITLE
after you update the mainnet，my read node keep at  4564024 highestBlock all the time 

### ISSUE THREAD

**Issue by mtyou** [Fantom-foundation/go-opera#96]
today update the mainnet to go-opera,my read node keep at 4564024 highestBlock all the time ,this block is the last one before upate,what shoul i do for that ?

**Comment by quan8** [comment]
@mtyou  please ask our support team for a better instruction.

If your node is running go-lachesis 1.0.0-rc0 and is running the migration (check server's log), then just keep it running. It will take 1 hour or more depending on your machine specs. 

Alternatively you may move to go-opera 1.0.0-rc1. See the following guide:
https://github.com/Fantom-foundation/lachesis_launch/blob/release/opera-v1.0.0-rc1/docs/setup-readonly-node.sh
