### ISSUE TITLE
Where can I find fantom configuration documentation?

### ISSUE THREAD

**Issue by Ten-Ou** [Fantom-foundation/go-opera#97]
Hi ！
Excuse me, where can I view the parameter description document of the network.toml configuration file. I searched all the documents in the project and couldn't find it. Can you tell me? Thank you.

![image](https://user-images.githubusercontent.com/21339312/116674417-33612780-a9d7-11eb-9c8e-0d52c30b1149.png)

**Comment by chebykin** [comment]
The same problem for me. There is no public information about how to set up and configure an external observer node to watch `ftm` network.

**Comment by uprendis** [comment]
Hello All,
Good day to you!
Sorry for a late response
You can find the instructions for running go-opera for Opera mainnet/testnet here: https://github.com/Fantom-foundation/lachesis_launch/tree/release/opera-v1.0.0-rc2
It doesn't include instructions for .toml configs specifically, but normally you don't need to use it - the most of configuration is doubled via the flags, the current list of which can be obtained with `opera help`. You can configure your node with flags first, and then export the resulting config: `opera --your-favourite-flags dumpconfig`

Also, we try to keep some parts of it as close to `geth` as possible, and some parts are even exactly or almost exactly the same as in `geth` (such as EVM, configuration of API endpoints, networking, datadir, keystore)
